### ISSUE TITLE
Check livery over MP, for some users loads up the default one only.

### ISSUE THREAD

**Issue by JMaverick16** [NikolaiVChr/f16#100]

**Comment by NikolaiVChr** [comment]
This must be related to LOD.
Make them set High Detail Only for 2019.1.
Make them set Show high detail models" and set LOD high for 2018.3

**Comment by JMaverick16** [comment]
I've done that but at times it happened still, will further investigate.

**Comment by JMaverick16** [comment]
No further reports on this and unable to replicate, must have been LOD on the user-end.
