### ISSUE TITLE
Czech decal wrong in livery

### ISSUE THREAD

**Issue by NikolaiVChr** [NikolaiVChr/f16#105]
Czech decal is wrong, it should look like:

![image](https://user-images.githubusercontent.com/3764194/67358952-32d60e00-f562-11e9-812f-46c580f5fb14.png)

Reported by V12

**Comment by JMaverick16** [comment]
Czech Air Force has no F-16s, only Gripens and L-159s. What he sees wrong is the Dutch roundel which is correct.
