### ISSUE TITLE
Add sun reflection and frost on canopy (like F-15)

### ISSUE THREAD

**Issue by JMaverick16** [NikolaiVChr/f16#107]

**Comment by NikolaiVChr** [comment]
When DDS cache is enabled the frost mipmapping acts strange.

So frost cannot be added.

**Comment by NikolaiVChr** [comment]
Verified that this is not a renderbin issue.

**Comment by JMaverick16** [comment]
Almost complete thanks to 7c17ba01039139b2fad009043adc4688e4803840 .
Only need frost effect but that will require A/C IIRC.

**Comment by NikolaiVChr** [comment]
fixed
