### ISSUE TITLE
Remove weapons from Payload dialog

### ISSUE THREAD

**Issue by NikolaiVChr** [NikolaiVChr/f16#112]
Remove weapons from Payload dialog to make the dropdown list on pylon 3 & 7 shorter.

Max should be 18 options in each dropdown menu.

I suggest removing from pylon 3 & 7:
- Nukes
- Travel pod

And put those in quick select dialog instead.

**Comment by l0k1** [comment]
To combat this in the MiG-21 I created a new weapons selection dialog that can handle much more armament - 21 categories with 21 loads each iirc. 


![](https://media.discordapp.net/attachments/609668637816651776/632864421840158721/unknown.png)

It shouldnt be hard to port over if there is desire.

**Comment by JMaverick16** [comment]
Does it still needs to be done?
Keep in mind that nukes don't have and won't have a quick payload option so they can't be removed from there.

**Comment by JMaverick16** [comment]
> I suggest removing from pylon 3 & 7:
> 
> * Nukes
> * Travel pod
> 
> And put those in quick select dialog instead.

As of May 2020: Travel pod, nukes, 1x AGM-65 options are only available through payload options dialog, reducing by four the total for said pylons.

**Comment by JMaverick16** [comment]
Will close this as nothing will be changed until last lot of weapons will be started.
