### ISSUE TITLE
Add key binding for target in middle of HUD

### ISSUE THREAD

**Issue by vanosten** [NikolaiVChr/f16#115]
Please consider adding a key binding (e.g. "Y" Shift-Y) for "Select target track center most in HUD" like in the Viggen. 

When there are many targets (e.g. on ground) it is tedious, time consuming and error prone to cycle through all targets with "y".

(Fine keeping the Crtl-y for deselecting a target).

**Comment by NikolaiVChr** [comment]
Shift-Y is used for selecting prev. target. So has to be another key.
Suggestions?
'i' maybe..

**Comment by vanosten** [comment]
As far as I can see in /f16-base.xml lines 595 and 1210 crtl-y is used for deselect. I might of course be wrong.

**Comment by NikolaiVChr** [comment]
It is now 'i'. Fixed.
