### ISSUE TITLE
Hydra-70 is a bit too picky for aiming

### ISSUE THREAD

**Issue by vanosten** [NikolaiVChr/f16#116]
After having shot a lot of Hydra-70 against OPRF-asset "gasometer" (part of depot), I believe that the algorithm does not take into account the size of the target. It looks like that you only get a hit if you are hitting the center bottom (0, 0, 0) within little margin. 

Getting hits with the gun is much easier - at the same time the visual blast when hitting a target or the ground indicates that it should hit a bit harder (more often).

**Comment by NikolaiVChr** [comment]
Yes it does not. All models have same size bounding box which is what the hit checks for.
The gun/hydra hitting code have to be completely reworked to be able to get hit messages like missile-code does it.

**Comment by JMaverick16** [comment]
Try to check how the messaging is done in the A-10 where the rocket hits report the impact distance instead of hit/miss

**Comment by NikolaiVChr** [comment]
It now has a CCIP aim. Fixed.
