### ISSUE TITLE
MFD display AMD lighting issue

### ISSUE THREAD

**Issue by Adamdoesgit** [NikolaiVChr/f16#137]
Potential source of issue in f16/Models/Effects/displays/lcd.frag on line 103:
```
color = clamp(color+specular.rgb+ambient/*+diffuse*/, 0.0, 1.0);
```
Commenting out the diffuse component resolves the issue for me.

**Comment by NikolaiVChr** [comment]
Since specular works fine, its not the normal thats the issue.

**Comment by NikolaiVChr** [comment]
gl_FrontMaterial.diffuse.rgb is white
It should be black for MFD.

Note to self: test this on NVidia

**Comment by NikolaiVChr** [comment]
I decided to commit a workaround for this.
On radarSystem branch. 20637fc517cc261130db5738833aec181eccc796
