### ISSUE TITLE
Temparature gauge for afterburner

### ISSUE THREAD

**Issue by NikolaiVChr** [NikolaiVChr/f16#140]
the gauge currently ignores afterburner.

**Comment by NikolaiVChr** [comment]
> The maximum temperature for FTIT would be reached at MIL power. Being in afterburner should have no change on your FTIT reading, since the sensors are forward (upstream) from the afterburner section.

@legoboyvdlp

**Comment by legoboyvdlp** [comment]
Thanks :+1:
