### ISSUE TITLE
Add key to clear drag chute after use.

### ISSUE THREAD

**Issue by JMaverick16** [NikolaiVChr/f16#145]

**Comment by JMaverick16** [comment]
A "Repack" option has been suggested as well (should be good in COnfig menu).

**Comment by JMaverick16** [comment]
Adding the 3D switch to MLU MISC panel could be used for both deploy and release. Repack option then available in config menu.

**Comment by legoboyvdlp** [comment]
Repack + key done. 3D + animation needed!

**Comment by JMaverick16** [comment]
On Mac ctrl-F5 doesn't do anything when full stopped so the chute stays there till I click repack on config dialog. Is it meant to be or there's something wrong?

**Comment by JMaverick16** [comment]
This has been completed, therefore I'm closing since MISC panel is a separate deal.
