### ISSUE TITLE
Add CCRP release timer to HUD

### ISSUE THREAD

**Issue by JMaverick16** [NikolaiVChr/f16#146]

**Comment by NikolaiVChr** [comment]
There is not really room for it, due to having Pilot and Type of target. Those two were not in real aircraft so there was room.

**Comment by JMaverick16** [comment]
Ah I see... There's no way to add extra room for it or result would be cluttered? Maybe by placing it over either pilot name or a/c type once the target is locked with TGP?

**Comment by Rudolf339** [comment]
Just to drop my two cents in here, target callsign and aircraft type can be seen in the DED display IFF page, which isn't that much out of the sight and a bit more realistic

**Comment by NikolaiVChr** [comment]
That is true Rudolf. So which do you guys want to sacrifice?

**Comment by JMaverick16** [comment]
Target callsign is more important IMO, because you can reference instantly who you are targeting. Then with IFF you can ID what it is flying or which asset it is. But I'd say the timer comes up on CCRP mode only so maybe it sacrifices that part when in that mode.

**Comment by JMaverick16** [comment]
Added with 4e6b41b

**Comment by legoboyvdlp** [comment]
@JMaverick16 I somehow doubt that commit added it

**Comment by NikolaiVChr** [comment]
No clue what commit that is. But its added.
