### ISSUE TITLE
Guided bombs enhanced effects (LAU-68, CBUs)

### ISSUE THREAD

**Issue by NikolaiVChr** [NikolaiVChr/f16#147]
With Thorstens e253beaba54b61123d08cd65813f82d01ca0b275 unguided bombs now have craters and enhanced effects.

Craters and smoke is done auto, but could port explosion effects over to other A/G weapons:

Use AGM65 effects for 125 lbs warheads.
Use MK-82 effects for 200 lbs warheads.
Use MK-83 effects for 450 lbs warheads.
Use MK-84 effects for 950 lbs warheads.

**Comment by JMaverick16** [comment]
Ported explosion to all weapons except AGM-158 (should require an effect twice as big as the MK-84), LAU-68, CBU-87/105 and B61s.

**Comment by JMaverick16** [comment]
I'll close this as it's been completed and eventually open a separate one for rockets.
