### ISSUE TITLE
Decrease A/B visibility in daytime

### ISSUE THREAD

**Issue by JMaverick16** [NikolaiVChr/f16#158]
https://live.staticflickr.com/115/310426895_7fd4bc6115_b.jpg
In bright conditions, flame should be less visible than it is now.

**Comment by NikolaiVChr** [comment]
Thats how I made it, then you complained and it was made visible during daytime again.

**Comment by JMaverick16** [comment]
Really? Lol I forgot. Well maybe set it something in between.

**Comment by NikolaiVChr** [comment]
Its now almost invisible during daytime.
Fixed.
