### ISSUE TITLE
Tail light showing s/n

### ISSUE THREAD

**Issue by JMaverick16** [NikolaiVChr/f16#159]
Reference: http://www.hottail.nl/basevisits/2007/0226-Volkel/Index.html

**Comment by NikolaiVChr** [comment]
This wont look real good until compositor.
This light is not present on all blocks/MLU-tapes.

**Comment by JMaverick16** [comment]
I've seen it on various at least later MLUs, Block 40/50.

**Comment by JMaverick16** [comment]
Completed with baaca919acdf28fc7fb8c0f5d020b58343daacc7
