### ISSUE TITLE
Dogfight mode

### ISSUE THREAD

**Issue by NikolaiVChr** [NikolaiVChr/f16#161]
A mode where its easier to lock up visual targets, and cannon and sidewinder should be available.
It should also open specific MFD and DED pages. And declutter HUD.

**Comment by NikolaiVChr** [comment]
So the following is planned to happen in DGFT mode: (Thanks to reaper for some of the suggestions)
- Radar silent
- Switch to guns
- HUD declutter
- MFDs to certain pages (CRM/WPN)
- DED to certain page (CM)

If radar is turned on in DGFT it will go into ACM 30X20X10 and lock up closest target automatically. CTRL-d can still unlock. The ACM cannot be changed until leaving DGFT.

I think I will not limit what weapons can be chosen...for now

Dogfight key will be a toggle.

**Comment by NikolaiVChr** [comment]
![image](https://user-images.githubusercontent.com/3764194/80275349-f0dc7f00-86e0-11ea-86d3-389738dda110.png)

**Comment by NikolaiVChr** [comment]
MFD CRM should say ACM and 20.

**Comment by NikolaiVChr** [comment]
So the radar needs for ACM:
- [ ] autolock
- [ ] max 10nm
- [ ] limit for (more involved that sounds as FoR now travels with attitude)

When turning off ACM:
- [ ] go back to last for
- [ ] go back to last nm?
- [ ] remember current track

**Comment by NikolaiVChr** [comment]
Will close this issue when removing key 'y' from selecting targets outside DGFT mode.

**Comment by JMaverick16** [comment]
Could the half circle attitude indicator be included as well?

https://i.ytimg.com/vi/IUpkh2rvCDo/maxresdefault.jpg

**Comment by NikolaiVChr** [comment]
Needs testing now
