### ISSUE TITLE
FBW gear down gains

### ISSUE THREAD

**Issue by NikolaiVChr** [NikolaiVChr/f16#170]
Right now the FBW help you keep around 11 AoA degs on approach.
In the prototype FBW diagrams its about 6. But that kept 11 to 15 AoA hard to keep.
In the diagram the lag on the gain bias changes is much slower.

Now this gives issues when for example lower gear at 200 KCAS and the aircraft naturally want to pitch up to help with that AoA.

It also gives issues after takeoff, it again wants naturally to pitch up.

**Comment by NikolaiVChr** [comment]
Here is the system with the issue from AD-A055-417:
![image](https://user-images.githubusercontent.com/3764194/79077937-2e1a3780-7d05-11ea-84ad-4f420daaa188.png)

**Comment by NikolaiVChr** [comment]
I will first experiment with going back to diagram lag, and then increase lag on the BIAS +6 (+11) from WoW.

**Comment by JMaverick16** [comment]
From what I tested so far, landing feels much less "brutal" in terms of pitch up or down, with aircraft doing almost zero sudden changes in AoA when gear is lowered, therefore more stable.
Take off still requires you to pull the stick further and therefore it pitches up more than wanted after leaving the ground, often needing some pitch down input to prevent it going further up. This checked with minimal (clean or 1 central bag) or basic loads (2 bags, dummy missiles).

**Comment by LJQCN101** [comment]
The GD's analog FLCS block diagram shown above does not contain take-off & landing gains. You should refer to ADA189675 (DFLCS FSD block diagram) for take-off & landing gains.

AFAIK, AOA feedback is not used below 10 deg AOA. FBW won't hold a specific AOA, but to command nose down if you exceed 10 deg.

![AOA feedback](https://user-images.githubusercontent.com/14259702/93752412-3621c000-fc31-11ea-9fe0-f9ef6aa97f1f.jpg)

**Comment by NikolaiVChr** [comment]
> The GD's analog FLCS block diagram shown above does not contain take-off & landing gains. You should refer to ADA189675 (DFLCS FSD block diagram) for take-off & landing gains.

Thats strange, especially considering the the part shown above is exactly that, landing, take-off and refuel gains. And there are more gain changes for those conditions in the full diagram.

> AFAIK, AOA feedback is not used below 10 deg AOA. FBW won't hold a specific AOA, but to command nose down if you exceed 10 deg.
> 
> Also, it uses pitch rate * 0.5 instead of (Nz - 1.0) in the feedback loop.

That on the other hand is interesting. The old diagram does still have Nz fed into the system while AoA is ignored when rolling and rotating.
I would love to really make that 1987 diagram, but sadly its barely readable, some things can be infered by looking at older diagrams and some common sense, but far from everything.

Apropos infering, I am guesstimating that note 7 is 'WeightOnWheels for MLG', if that's the case its interesting that the lead-lag filter is bypassed when not airborne.

**Comment by LJQCN101** [comment]
> The old diagram does still have Nz fed into the system while AoA is ignored when rolling and rotating.
Yup, while the real jet (regardless of Analog or Digital FLCS) doesn't use Nz feedback in takeoff & landing gains, as I checked through T.O. manuals of different blocks. So I think if you're using the Analog FLCS diagram as a basis, some modifications are required for the missing functions i.e. pitch rate & AOA feedback, CAT III, roll departure prevention system etc.

**Comment by NikolaiVChr** [comment]
CAT III is made long ago. So is departure prevention/recovery, except if you fly the YF-16. And MPO system and other things not in that diagram.

I made an experimental change that incorporate some of those things in that diagram @LJQCN101 , and so far people are liking it.
I had initially dismissed using that diagram due to it being so low quality. But you are right, some things can be gotten from it. Thank you. 👍

**Comment by LJQCN101** [comment]
Hi,

I'm recently playing with this mod and found that some implementations of the 1987 diagram is not correct. One example:

[code]
<fcs_function name="fcs/fly-by-wire/pitch/q-product-1987">
            <description>The 1987 diagram has 0.5 gain on condition-z, but its feedback gains is double of the 1975 diagram. So it is halved to 0.25</description>
            <function>
                <sum>
                    <product>
                        <property> fcs/fly-by-wire/condition-z </property>
                        <value> 0.25 </value>
                    </product>
                    <product>
                        <property> fcs/fly-by-wire/condition-y </property>
                        <value> 0.167 </value>
                    </product>
                </sum>
            </function>
        </fcs_function>
[/code]

This 0.167 gain is applied to the washed-out pitch rate, but not pitch rate itself. It is then added to the normal acceleration feedback path.

The 0.25 gain however should be applied to pitch rate itself, and then joins the pitch rate feedback path.

So the q-product-1987 cannot be implemented like this.

I've modified and fixed some logics according to the 1987 diagram at my repo: https://github.com/LJQCN101/fg-f16-flcs-test
But I haven't checked for the prototype FBW yet. Maybe later I'll make a pull request.

For some details in the diagram, you can check some of my answers here:
https://www.f-16.net/forum/viewtopic.php?f=2&t=58462
https://www.f-16.net/forum/viewtopic.php?f=21&t=53703&start=15
https://www.f-16.net/forum/viewtopic.php?f=23&t=56546

Regards,
LJQC

**Comment by NikolaiVChr** [comment]
Thank you @LJQCN101 , the 1987 system is disabled for now btw.
I am not active in dev of this aircraft at the moment, but I will look into it when I get active again.
