### ISSUE TITLE
Kneeboards implentation

### ISSUE THREAD

**Issue by JMaverick16** [NikolaiVChr/f16#173]

**Comment by NikolaiVChr** [comment]
So what kind of info should there be?

Basically there is 2 ways of doing this:

The mig21 way: Have a text file, and that gets loaded onto the kneeboard when starting up FG.
The auto way: Generate some auto info.
Mix way: Auto on 1 knee, and file-text on other knee.

**Example of auto gen info**
Take-off base: ILS freq and which runways is available.
Maybe some bases close to the route with ILS/rwy info.
Callsigns of Link16 contacts.

**Example of file-text info**
Rules of engagement
Awacs and link16 callsigns
Info on specific airbases
Mission briefing

**Comment by JMaverick16** [comment]
Mix way is the way IMO

**Comment by NikolaiVChr** [comment]
Initial implementation: 540b62dfc1abd7c16ef57b728385b07a36c501fa

**Comment by NikolaiVChr** [comment]
Now waiting for feedback..

**Comment by JMaverick16** [comment]
Gimme 2.5hrs

**Comment by NikolaiVChr** [comment]
Timi found a kneeboard that fits this paper size:
Junior Legal | 127 x 203 mm | 5.0 x 8.0 in | 1:1.6

**Comment by NikolaiVChr** [comment]
HAF checklist pages are about:
3.3" x 9"

**Comment by NikolaiVChr** [comment]
Ours right now is:
6" x 8.5"

**Comment by NikolaiVChr** [comment]
They are now the size Timi found.

**Comment by NikolaiVChr** [comment]
Marking this as fixed
