### ISSUE TITLE
Cold and Dark?

### ISSUE THREAD

**Issue by NikolaiVChr** [NikolaiVChr/f16#176]
@JMaverick16 / Reaper, I don't understand.

So for cold and dark you want:
* HUD Symbology turned off.
* Console and instr light not turned off.
* Radar turned off.
* Ext. light on?
* DED brightness on?
* MFD brightness on?

I don't get why some things off and some on.

I think we need some consistency. Discuss..

**Comment by JMaverick16** [comment]
HUD Sym off (IRL you would have to increase it manually), Stby ADI needs to be "uncaged", Master ext lights off. Rest is fine right now IMO.

**Comment by JMaverick16** [comment]
Things to be added to cold and dark:

- HUD Symbology OFF.
- Console, instr, etc. lights OFF.
- Master ext lights OFF.
- Stby ADI uncage.
- "Fake" INS ALIGN (DED page when starting up that show progress, maybe just with a timer).

Tell me what you think.

**Comment by JMaverick16** [comment]
Updated list after yesterday's BMS stream.

**Comment by JMaverick16** [comment]
Updated cold and dark todo list after dd22c0e93026e73f6e2c0a31975a12c443b30505 :

- HUD Symbology OFF.
- Air Source OFF (avionics cooking).
- Stby ADI uncage.
- "Fake" INS ALIGN (DED page when starting up that show progress, maybe just with a timer).
- RWR switch in EW panel OFF.
- Oxygen switch OFF.

**Comment by NikolaiVChr** [comment]
- [x ] HUD Symbology OFF and switch wheel.
- [ ] Air Source OFF (avionics cooking).
- [ ] Stby ADI uncage.
- [ ] "Fake" INS ALIGN (DED page when starting up that show progress, maybe just with a timer).
- [ ] RWR switch in EW panel OFF.
- [ ] CM switches OFF
- [ ] RWR power button
- [ ] Oxygen switch OFF.
- [x ] Console, instr, etc. lights OFF.
- [x ] Master ext lights OFF.
- [ ] Add to autostart
- [ ] Add to checklists

**Comment by NikolaiVChr** [comment]
Leaving this as fixed.
You can open up issues for the remaining things if needed.
