### ISSUE TITLE
JHMCS implementation.

### ISSUE THREAD

**Issue by JMaverick16** [NikolaiVChr/f16#181]
Because yes. Even if I'd need to pay for it.

**Comment by NikolaiVChr** [comment]
Probably too new a technology to put in our aircraft.
Our aircraft is more likely to have the DASH system.

I not gonna make this, its gonna be choppy when moving head if done with canvas.

**Comment by JMaverick16** [comment]
DASH could still be added as a toggle option in config menu. I know it's really advanced but could still be added without aiming or target tracking feature. Also, of the head movement is an issue, one wouldn't use it. I'd it's still worth considering.

**Comment by JMaverick16** [comment]
I've texturized the dedicated panel for Symbology Int which is now available for all Blocks apart from MLU which uses the HMD panel including RF.

**Comment by legoboyvdlp** [comment]
yes

**Comment by JMaverick16** [comment]
This is (almost) complete as of mid-May 2021

**Comment by NikolaiVChr** [comment]
fixed
