### ISSUE TITLE
Checklist colour

### ISSUE THREAD

**Issue by legoboyvdlp** [NikolaiVChr/f16#182]
Hardpoint items, I believe, should always be green:

![image](https://user-images.githubusercontent.com/10434911/81116366-22ddb480-8f1d-11ea-8498-da9fd9cea271.png)

**Comment by legoboyvdlp** [comment]
Also, a proper shutdown checklist, perhaps? Like, returning to cold / dark state?

**Comment by JMaverick16** [comment]
I'd say green if you don't have any targeting pods mounted.

**Comment by NikolaiVChr** [comment]
c1792666bd0cd6c2d10e9f8f3c9c4481bde0a910 fixes this
