### ISSUE TITLE
Flood Console knob in int lighting not working

### ISSUE THREAD

**Issue by JMaverick16** [NikolaiVChr/f16#184]
Doesn't have any functions tied to it I think.

**Comment by NikolaiVChr** [comment]
There is flood light for console and instr panels.
Whats should the difference be?

**Comment by JMaverick16** [comment]
That's the problem. The others do something while this knob doesn't. And I'm wondering why.

**Comment by NikolaiVChr** [comment]
Okay.
instr panel is center console
console panel is left and right consoles

**Comment by NikolaiVChr** [comment]
95658f900c0d3178814b91fa998783100ed56da2 fixed it
