### ISSUE TITLE
Keys for walker stopped working properly

### ISSUE THREAD

**Issue by NikolaiVChr** [NikolaiVChr/f16#186]
a and w key specifically, maybe others.

**Comment by JMaverick16** [comment]
Mmm works correctly for me, unless it got broken in 2020+.

**Comment by Marsdolphin** [comment]
Dunno if it is the same problem but when I test newest F-16 in KXTA:

> I can't use the arrow keys, after lock press e nothing happens etc a lot of stuff is wrong right here
Don't know why

**Comment by NikolaiVChr** [comment]
Nevermind, works for me
