### ISSUE TITLE
Review canopy operation when BATT on.

### ISSUE THREAD

**Issue by JMaverick16** [NikolaiVChr/f16#189]

**Comment by NikolaiVChr** [comment]
I did a triple check of this. Both in block 15 and 50 MAIN PWR switch have to be in OFF to get battery to open/close canopy. Else you need exterior power or main generator running.

![image](https://user-images.githubusercontent.com/3764194/81503866-4a020080-92e6-11ea-9988-737d2c499f98.png)
![image](https://user-images.githubusercontent.com/3764194/81503855-35be0380-92e6-11ea-9dc3-c269e70a848e.png)
