### ISSUE TITLE
Screen and other problems

### ISSUE THREAD

**Issue by kwanzapili** [NikolaiVChr/f16#200]
I recently updated FG to 2020.1.1 and since then I have some weird appearances with  the latest F16 in several views:

- In the cockpit, the screens are generally white. For higher numbered variants, the whole cockpit is rendered in black and white. Nothing appears in them - just the outlines.

- In other views, there are large black rectangular blocks around the wing tips and tail. They seem to be created once autostart is initiated.

I have tried various master clones and all have the same issues. These issues appear unique to the F16 - other planes work just fine. So I infer that that the problem lies with something in the F16 files. 

Is is just me who sees these ghostly appearances?

**Comment by legoboyvdlp** [comment]
Do you have an Intel graphics card?

ALS or Rembrandt or default?

**Comment by JMaverick16** [comment]
I'd also add to specify which are your shader options. :)

**Comment by NikolaiVChr** [comment]
I bet he is using Compositor.
We have not made the F-16 compositor ready yet, as we dont want to maintain 2 builds of F-16. So until compositor becomes standard (probably 2020.2.1) we wont properly support it.

**Comment by kwanzapili** [comment]
I use an old Nvidia card (GeForce GTX 550 Ti). In my .fgfsrc I have  `--disable-rembrandt` and `--shading-smooth` - I guess that means ALS is on? I think that previous comment points to the potential issue. I do have Compositor on - it flashes _Compositor_ during the screen splash. Is compositor meant to make things faster/better - is it similar to compositing in window managers? I don't seem to see any option to toggle it on/off for specific sessions. Perhaps I'm missing something?

**Comment by NikolaiVChr** [comment]
Compositor is not finished yet, its mainly for people who wants to test it as an upcoming feature.
Not sure what you did to get a compositor build, but F-16 does not support it until its the default renderer.
When you installed Flightgear it should give you 2 shortcuts: one with compositor and the normal one without.
Compositor is not faster, it brings features such as shadows.

**Comment by kwanzapili** [comment]
Thanks a lot. That is very helpful. I'll reinstall FG without compositor enabled. Maybe, I've also get fewer segmentation faults without it :).

**Comment by legoboyvdlp** [comment]
@kwanzapili no need to reinstall, there is both fgfs-compositor.exe and fgfs.exe :)

**Comment by kwanzapili** [comment]
I can confirm that compositor was the issue. I can now see the cockpit screens. Just a couple of side issues. I get an error message at startup
`[ERROR] Radar system missing or uninit (frame notifier)`
This is before I take off. 
Also, I cannot get my arrow keys to work any more, but the keys on the numpad seems to work. Not sure why.

**Comment by legoboyvdlp** [comment]
The first error is harmless, simply means the radar is not initialized yet.

The arrows now control the cursor on the CRM page of the MFDs. Mouse control (and numpad) still work o.k.

**Comment by NikolaiVChr** [comment]
Thats by design.
The arrow keys now control the radar cursor (together with key 'l'), in future update here in 2020, you will no longer be able to use y key to lock up next target unless your radar is in ACM mode (dogfight override mode).
So those arrow keys will be come pretty significant, so if you dont control with mouse or stick you have to use numpad.

**Comment by NikolaiVChr** [comment]
haha, you already answered lego, I was too slow

**Comment by kwanzapili** [comment]
Thanks everyone. All is clear now.
