### ISSUE TITLE
MFD SWAP

### ISSUE THREAD

**Issue by NikolaiVChr** [NikolaiVChr/f16#201]
Requested by Reaper

**Comment by JMaverick16** [comment]
Option to get "NOT SOI" indications as well?

**Comment by NikolaiVChr** [comment]
NOT SOI would never show in the way we have set things up, so no.

Once we get TGP image inside the MFD things will change and we might need it.

The only thing missing right now is the border on the FCR page. And that would totally mess up the text placed by Richard, and would require total rework of some of MFD code. Definitely not worth it, just to get a border.

**Comment by NikolaiVChr** [comment]
fixed
