### ISSUE TITLE
HUD symbols dim for some users

### ISSUE THREAD

**Issue by NikolaiVChr** [NikolaiVChr/f16#203]
In ALS

**Comment by Reaper313sqn** [comment]
![fgfs-20200509192241](https://user-images.githubusercontent.com/65277123/83004633-32c65100-a010-11ea-800c-da133df8daf4.png)
![fgfs-20200401172839](https://user-images.githubusercontent.com/65277123/83004636-33f77e00-a010-11ea-8a6f-c9f0fb0c4c1a.png)
![fgfs-20200401174218](https://user-images.githubusercontent.com/65277123/83004638-34901480-a010-11ea-840b-512075387f54.png)
![fgfs-20200401174235](https://user-images.githubusercontent.com/65277123/83004643-3528ab00-a010-11ea-8b58-b14b356304e6.png)
![fgfs-20200401174732](https://user-images.githubusercontent.com/65277123/83004645-35c14180-a010-11ea-82f8-45869a3a7a26.png)

**Comment by Reaper313sqn** [comment]
How hard would it be to make an option to use the non-ALS HUD when using ALS? Would it need a complete rework of the HUD or not? If not, I'd be very happy (alongside many other Intel users) if somebody could do this.

**Comment by JMaverick16** [comment]
#137

**Comment by NikolaiVChr** [comment]
> How hard would it be to make an option to use the non-ALS HUD when using ALS?

Not sure, I could look into it.

**Comment by NikolaiVChr** [comment]
In half an hour I will commit so you can switch between this:

![image](https://user-images.githubusercontent.com/3764194/95666427-c892f080-0b59-11eb-9945-3f3692c50518.png)

And this:

![image](https://user-images.githubusercontent.com/3764194/95666431-d5afdf80-0b59-11eb-8174-eac50971bd94.png)

**Comment by NikolaiVChr** [comment]
@Reaper313sqn this should fix your issue:

![image](https://user-images.githubusercontent.com/3764194/95667394-b5861d80-0b65-11eb-8ccd-57b43caa0fe8.png)

**Comment by NikolaiVChr** [comment]
05a81d8ec6ac7106a58c3b07a8398b953555581c might have fixed this without having to use the setting.
