### ISSUE TITLE
Cold and Dark option

### ISSUE THREAD

**Issue by JMaverick16** [NikolaiVChr/f16#206]
To quickly shutdown the jet without needing to cutoff or run through the checklist.

**Comment by JMaverick16** [comment]
Basic implementation with 74eb81f , requires check.

**Comment by legoboyvdlp** [comment]
fairly sure this is done?

**Comment by JMaverick16** [comment]
Needs code review and confirmation I haven't messed it up. Also some switches might need to get added.

**Comment by JMaverick16** [comment]
I assume this got fixed with 74c3da14aa2764c6fb5f3fb74b257efdaf263def ?

**Comment by JMaverick16** [comment]
Closing this.
