### ISSUE TITLE
Add PFD display above warning panel

### ISSUE THREAD

**Issue by JMaverick16** [NikolaiVChr/f16#213]
Pilot Fault Acknowledgement display has same dimensions as DED, hence it would just be copy/pasted in the right position and set to to show only the F-ACK page.

**Comment by legoboyvdlp** [comment]
Did you add a model? Because it is relatively easy to do the nasal, happy to do this also, but not sure did you push the model  you showed yet?

**Comment by JMaverick16** [comment]
What I pushed was an xml reusing the same model of the DED, which has the center somewhere very far from the model, hence I should clone the 3D, recenter it and reposition both the new PFD and the warning panel.

**Comment by JMaverick16** [comment]
Needs reposition to be finished
