### ISSUE TITLE
Navigation beacons visible on HSD

### ISSUE THREAD

**Issue by Reaper313sqn** [NikolaiVChr/f16#216]
Hello!

On a video I have seen that the HSD can show nav beacons and some other stuff. I still have to do some research on what exactly can be showed. The video reference is a RNLAF F-16AM M2 simulator. The video also shows that these beacons can be selected with the stick. More information will follow.

Regards,
Reaper

**Comment by NikolaiVChr** [comment]
Oh, please post some stills from the video when that is showed.

**Comment by NikolaiVChr** [comment]
No response or further details on this. Closing.
