### ISSUE TITLE
Order of ICP buttons and DED pages

### ISSUE THREAD

**Issue by Reaper313sqn** [NikolaiVChr/f16#218]
This should be not much work code-wise; the problem is information.

Pages 1-6 are all correct as far as I know. I am not sure of page 8 and 9, I don't know if there is any evidence for this.

Page 7 and 0 are not correct for sure. Page 7 'MARK' should be BINGO page, can provide reference for this. Also the 'RCL' button is likely to be incorrect as this probably serves as backspace.

Thus, pages 7-0 and 'RCL' are likely to require some work.

**Comment by legoboyvdlp** [comment]
Actually, DED requires work overall.

These buttons are so-called "PRIORITY" that the first time, show the page, then second time go back to last DED page. 

If the last DED page was another "override", then it goes back to "CNI".


M-SEL is indeed "mode-select". 
RCL is RECALL, which rejects last input and returns last valid data.

**Comment by Reaper313sqn** [comment]
This is true, as I have read lately. Additionally, the pages that are less frequently used (and that do not fit among the normal buttons) are listed under 'LIST'.

**Comment by JMaverick16** [comment]
Tomorrow I'll provide pics from BMS and DCS about the LIST page. Dunno if there are actual sources available.

**Comment by legoboyvdlp** [comment]
Yes, in fact I already added it 😛
