### ISSUE TITLE
HUD color brightness

### ISSUE THREAD

**Issue by JMaverick16** [NikolaiVChr/f16#219]
Green shade should be less intense, more similar to current DED font color. Also adding the reflection circle would be nice.

**Comment by NikolaiVChr** [comment]
The HUD symbols and text is much brighter than the DED.
You are tricked because of the dark DED background.

**Comment by NikolaiVChr** [comment]
After rereading, I must say I don't understand what you want..

**Comment by NikolaiVChr** [comment]
The HUD does not have dark background, it can never appear like the DED.
You mean less white?

**Comment by JMaverick16** [comment]
Yeah, slightly less white would be better IMO. Or at least make so that the lighting changes depending on time of day (like the AB does, however it is done): e.g. brighter in daytime (like it is now) and more greenish at night.

**Comment by JMaverick16** [comment]
8e869d418d30dc15a38d70f9c8f0bfdf7e64c7d7 Fixes it
