### ISSUE TITLE
Better IFF ID on MFD/HUD

### ISSUE THREAD

**Issue by JMaverick16** [NikolaiVChr/f16#221]
Probably manuals cover this aspect better but main point should be:
- Easier distinction between friendly and foe targets on MFD.
- Remove A/C type from HUD and leave it to IFF DED page + add what should be there IRL.
- Add further contact info on CRM dots.
- Animate IFF panel.

Any suggestion, further knowledge on the subject is highly appreciated! Will keep this issue updated as new features are raised.

**Comment by NikolaiVChr** [comment]
Not relevant anymore
