### ISSUE TITLE
RWR goes gray

### ISSUE THREAD

**Issue by legoboyvdlp** [NikolaiVChr/f16#232]
![image](https://user-images.githubusercontent.com/10434911/89717353-b9eb5a00-d9ad-11ea-80ba-221b5133622f.png)

**Comment by NikolaiVChr** [comment]
ALS?
Shader quality level?
Sun position compared to aircraft?
Time of day?
Anybody done stuff to the RWR model/shading while I was away?
FG version?

**Comment by JMaverick16** [comment]
> Anybody done stuff to the RWR model/shading while I was away?


Don't think so, only touched database, colors and new outer circle.

**Comment by NikolaiVChr** [comment]
No response on this, so closing.
