### ISSUE TITLE
Fictional liveries to separate add-on repository.

### ISSUE THREAD

**Issue by JMaverick16** [NikolaiVChr/f16#235]
I guess it would be wise to free up some space to get them all packed into an external repository that people can download and include in their F-16 Models folder.
We should figure out a smart way to do it though, any ideas welcome. Who should host it? Leto or me?

**Comment by Reaper313sqn** [comment]
I support the idea. However, even if we move fictional liveries to a separate add-on, there still remain many to be dealt with.

I believe a smarter livery manager is the solution. I do not have the knowledge to do this but I think the best option is to sort them like this (in folders): country/air force > squadron > livery.

Tell me what you think.

**Comment by JMaverick16** [comment]
I think the best option is to sort them like this (in folders): country/air force > squadron > livery.

This for real ones or fantasy?

**Comment by Reaper313sqn** [comment]
Both actually. Fictional liveries could be regarded as a country/air force, so they will all be separated from the rest.

**Comment by JMaverick16** [comment]
I prefer having them sorted like this for real ones. You wouldn't notice the difference in the livery dialog anyhow. But fictional should go in a separate pack altogether

**Comment by NikolaiVChr** [comment]
I disagree. Keep them in the repo.
If they are separate, people are not going to use them.

**Comment by NikolaiVChr** [comment]
Another reason for keeping them in the repo is that when you fly in MP some may have them, other may not. Those that do not will not proper see your livery.

**Comment by JMaverick16** [comment]
Reason why I closed this. It's fine :)
