### ISSUE TITLE
DED inputs

### ISSUE THREAD

**Issue by NikolaiVChr** [NikolaiVChr/f16#270]
Now that @legoboyvdlp has enabled inputting numbers into DED, some more could be enabled:

ALOW: CARA ALOW (f16/settings/cara-alow)
ALOW: MSL FLOOR (f16/settings/msl-floor)
LSR: LASER CODE (f16/avionics/laser-code)
MAN: WINGSPAN (f16/avionics/eegs-wingspan-ft)

This can be used to turn on/off Tacview recording:
![image](https://user-images.githubusercontent.com/3764194/95280526-7ef28f00-0855-11eb-8485-1987e57a06ce.png)

I do not understand the CNI page bottom.
"M1 3C4 M4 1200"
- M1 is not enabled so the '1' should not be there.
- MC is not enabled so the 'C' should not be there. 
- C swapped with 4 (not need though since 'C should not be there)
- M4 should not be there as the '4' after the 3 says M4 is enabled.
- MAN should be at the end (before TACAN)

So it should be `M  34   1200  MAN` plus tacan.

From Tape 1:
![image](https://user-images.githubusercontent.com/3764194/95281320-2623f600-0857-11eb-99ce-13499db1ba7b.png)

Furthermore, since our font do not have inverted '*' they could be made to blink when editing until enter is pressed?

I cannot find the DATALINK pages. Pressing LIST and then ENTER would normally bring up the DLNK pages:
![image](https://user-images.githubusercontent.com/3764194/95280168-adbc3580-0854-11eb-8a30-ff5025fae492.png)
![image](https://user-images.githubusercontent.com/3764194/95280224-c9bfd700-0854-11eb-981d-990c1b10181f.png)
![image](https://user-images.githubusercontent.com/3764194/95280274-efe57700-0854-11eb-858a-34445af8a20d.png)

**Comment by NikolaiVChr** [comment]
Does the input system supports multiple inputs for same page?

Could use ENTER to go to next input, both after a input and before.

**Comment by legoboyvdlp** [comment]
Yes, 

But no, use the clickspots above and below the RTN - SEQ switch to move the cursor * * between positions. For instance, you can see this already on the TACAN ILS page.

**Comment by JMaverick16** [comment]
Could it be possible to add the functionality to input IFF codes as well?

**Comment by NikolaiVChr** [comment]
> Could it be possible to add the functionality to input IFF codes as well?

Done
