### ISSUE TITLE
Autostart when engine running will shut it down

### ISSUE THREAD

**Issue by NikolaiVChr** [NikolaiVChr/f16#276]
And post a message that it failed.

**Comment by ph-jake** [comment]
Why would you Autostart when engine is running? Autostart is designed for getting done quickly when starting the simulation, being cold and dark. Is this related to damage repair? Please provide a test scenario to get in such damage repair situation.

**Comment by JMaverick16** [comment]
Tailstrike on landing or get hit by guns/missile with only partial damage and need to repair before taking off again.

**Comment by NikolaiVChr** [comment]
Yep. Also, if people who attempt a manual start manage to start the engine, but give up on all the other things, and say f*** it and hit autostart to get the rest done.

**Comment by ph-jake** [comment]
So, was this addressed satisfactorily?

**Comment by JMaverick16** [comment]
Iirc Leto fixed it when refactoring it on a separate nas file. Right now engine is restarted by clicking repair damage if damaged. I'm not sure it should be like that, but as long as we all agree on how it has to act I think it's fine

**Comment by NikolaiVChr** [comment]
I only fixed the repair autostart. Jake fixed the normal autostart.

But I am also in doubt if it should be autostarted when doing repair. (it only does it if you selected autostart in launcher)

**Comment by JMaverick16** [comment]
I think it should be consistent overall. So one doesn't get surprises depending on how the sim is launched

**Comment by NikolaiVChr** [comment]
Okay, done now. I think we can close this issue.
