### ISSUE TITLE
FUEL_AL_needle1 shows up red in the model, but shows up white in the simulation.

### ISSUE THREAD

**Issue by ph-jake** [NikolaiVChr/f16#277]
The lower part of the AL needle is supposed to be red to indicate critical fuel imbalance. This is why the FR needle rides on top of the AL needle, covering the red part when not applicable. 

The view in Blender (with the FR needle removed)
![image](https://user-images.githubusercontent.com/70720757/95442846-2b1e9d80-095c-11eb-9856-c47dc6f3cda1.png)
The view in Flightgear (with the AL needle exposed)
![image](https://user-images.githubusercontent.com/70720757/95443043-5f925980-095c-11eb-9cc1-b7150e74d8cd.png)
It also looks as is the center hub needs to be made dark.

**Comment by NikolaiVChr** [comment]
e8f79f341767d012bb07e22ead99b142901c97e2 semi fixes this. It really need red texture to be properly fixed.

**Comment by NikolaiVChr** [comment]
0a14c3a34c555d4cd43cecaaa3ea0c11dac7d7b3 properly fixes it
