### ISSUE TITLE
MFD: Unable to get a TGP lock on carrier Eisenhover with latest changes

### ISSUE THREAD

**Issue by JMaverick16** [NikolaiVChr/f16#278]
I can achieve designate lock with the cursor on FCR but can't lock it visually with TGP, neither with designate neither with LOCK OSB.

**Comment by NikolaiVChr** [comment]
Ground targets? So both sea and surface contacts?

And what did you test it on? MP targets, carrier or AI?

**Comment by JMaverick16** [comment]
Only tested on sea targets. I could only try AI targets. Eisenhower carrier could not be selected even with radar (I slewed to it and after pressing designate multiple times it only blinked and disappeared on HUD soon after), while on another AI ship I could lock no problem but TGP couldn't do anything (I tried moving SOI around as well but didn't do anything different).
This was in SEA mode. CRM wasn't displaying anything while GM showed the dot but couldn't lock either with radar.

**Comment by NikolaiVChr** [comment]
I could lock a AI ground object just fine. Well after fixing #279 but that has not to do with designate.

As for AI carriers, they are sunk under water, so radar thinks they are occluded by terrain. This warrants a fix.

**Comment by NikolaiVChr** [comment]
48d7eb381a87a96f00bb2450b7d681478ec46eb4 fixes the carriers.

**Comment by JMaverick16** [comment]
I'm still unable to lock them with cursor (Eisenhower at least), forget it with TGP.

**Comment by NikolaiVChr** [comment]
There is 2 Eisenhovers.

When you start the sim there is one at LFTH.

If you start the AI Eisenhover scenario, there is 2 of them. (In same place I think)
They interfere with each other and confuses the radar, so it deselects it right after selecting it.

So just avoid starting the scenario.

**Comment by JMaverick16** [comment]
I have one Eisenhower at EGOD and the other at LIPA, so no I don't think they get messed up with each other. I will test it with Truman and the others to see if it still doesn't work.

**Comment by NikolaiVChr** [comment]
Fixed
