### ISSUE TITLE
Update help for 2020.2

### ISSUE THREAD

**Issue by NikolaiVChr** [NikolaiVChr/f16#283]
At very least these things needs explaining:

- Sensor of interest
- DED input and how to find the pages (I cannot even find DLNK page anymore)
- Some words about radar modes
- Some info on how the radar works in Dogfight mode

**Comment by JMaverick16** [comment]
(DLINK should be in LIST>MISC)

**Comment by JMaverick16** [comment]
Nvm, DLINK is on LIST > ENTR but when clicking nothing happens.
@legoboyvdlp Any clues why it's not displayed?

**Comment by legoboyvdlp** [comment]
DLNK fixed

**Comment by NikolaiVChr** [comment]
Okay, minimally done now.
There could be lots more info though..
