### ISSUE TITLE
Version 3.50

### ISSUE THREAD

**Issue by NikolaiVChr** [NikolaiVChr/f16#285]
Minimum issues that needs resolving:
- [ ] #284 Make video
- [x] #283 Update help
- [x] #122 Engine RPM
- [x] Complete SMS page: text alignment
- [x] LIST page: TCN item switches to TGP (if mounted) instead of nothing
- [x] ILS freq info doesn't work properly (decimal values not recognized, eg. 109.5 is 1095.00)
- [x] #291 Some DED pages can't be accessed from MISC when pressing eg. 3 then 4 when 3 is not available, requiring to go back to CNI and then LIST (this happens mostly on MISC).
- [x] The new panel in block 50 has LE FLAPS switch in the wrong position.
- [x] #298 Course deg doesn't work properly (two-digit values not recognized, eg. 45 becomes 0)
- [x] TGP new number values overlap zoom info
- [x] Make changelog
- [x] Bump version in -set.xml and readme.md
- [x] Upload to FGAddon
- [x] Change minimum FG version in -set file
- [x] Upload again to FGAddon with minor fixes
- [x] Announce on FG forums

**Comment by JMaverick16** [comment]
I would include the TODO list I made on Discord as well so that we fix those issues.

**Comment by NikolaiVChr** [comment]
I have no clue what issue you talk about.
Could you write about what the short lines mean @JMaverick16 ?

**Comment by JMaverick16** [comment]
What short lines?

**Comment by NikolaiVChr** [comment]
Issues that does not needs resolving:
- [ ] STBY/CLR labels.
-  [ ] Exterior JFS sound

**Comment by JMaverick16** [comment]
Added a few bugs I've discovered while flying at Hunter today.

**Comment by NikolaiVChr** [comment]
CLR label will clear all info from all SMS stations, so they can be reentered. Since our stations is only auto populated, am not going to put in a CLR label.

**Comment by JMaverick16** [comment]
#311

**Comment by NikolaiVChr** [comment]
Done
