### ISSUE TITLE
Crash at startup

### ISSUE THREAD

**Issue by NikolaiVChr** [NikolaiVChr/f16#3]
In Linux 5H1N0B1 reported with FG 2018.1.1:

`*** stack smashing detected ***: <unknown> terminated
Abndon (core dumped)`

**Comment by NikolaiVChr** [comment]
12787, who also uses Linux but FG 2017.3.1 just had the same crash.

**Comment by legoboyvdlp** [comment]
Just a thought, looks like it could be to do with line endings:

https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=766251

**Comment by NikolaiVChr** [comment]
Ah, will try to force git to use LF line-endings then.

**Comment by NikolaiVChr** [comment]
It was some custom shader effect code. Fixed.
