### ISSUE TITLE
FCR: More symbols

### ISSUE THREAD

**Issue by NikolaiVChr** [NikolaiVChr/f16#308]
![image](https://user-images.githubusercontent.com/3764194/96170098-73712900-0f23-11eb-93a3-f08607acaf21.png)

![image](https://user-images.githubusercontent.com/3764194/96170148-84219f00-0f23-11eb-877a-a56cf30f32da.png)

![image](https://user-images.githubusercontent.com/3764194/96170232-9f8caa00-0f23-11eb-8f2a-d2dd11fe70b1.png)

![image](https://user-images.githubusercontent.com/3764194/96170352-c4811d00-0f23-11eb-894b-5bfcbb034048.png)

**Comment by JMaverick16** [comment]
Can't wait for the second one

**Comment by NikolaiVChr** [comment]
Didn't have to wait long..
