### ISSUE TITLE
Air refuel should toggle fuselage brt knob

### ISSUE THREAD

**Issue by JMaverick16** [NikolaiVChr/f16#311]
It was made with setlistener but later removed because buggy. Would be good to have ti working before FGAddon push.

**Comment by NikolaiVChr** [comment]
I didnt remove it, I made it work.
Test it please. And no the knob wont move, the light will just go on.

**Comment by JMaverick16** [comment]
Ah lol ok. Then the knob needs the code as well.

**Comment by NikolaiVChr** [comment]
Why? You really think they would put a motor on the knob to move it around? I don't.

**Comment by ph-jake** [comment]
Same is true for the CRS knob on the EHSI when switching modes, that needs to be fixed too.
