### ISSUE TITLE
Add all MFD pages

### ISSUE THREAD

**Issue by Reaper313sqn** [NikolaiVChr/f16#312]
Hello,

As development of the F-16 is, of course, done by many people, there are many styles of coding.  This is not a big problem for separate systems, but in my opinion this should not be the case for the MFDs. I think it would be better if just one created all pages, and let the non-existing pages show something like: "BLANK" or "IN DEVELOPMENT". This way, we have just one easy system and it will be easier for different people to develop different pages.

If this was already the plan, please excuse me for wasting your time.

Regards,
Reaper

**Comment by JMaverick16** [comment]
This was partly addressed in #225

**Comment by JMaverick16** [comment]
Since there's already another issue opened for this, I'm closing
