### ISSUE TITLE
Bug in `impact_listener()`

### ISSUE THREAD

**Issue by colingeniet** [NikolaiVChr/f16#329]
In `f16.nas`, function `impact_listener()`, line 994.
The test `if (distance != nil)` is incorrect (remnant from older version of the code) as variable `distance` is undefined.
It should be `if (target != nil)`.

Funnily enough, the reason it does not cause an error is that `distance` is defined as global variable in `zoom-views.nas`, which lives in the same namespace as `f16.nas`.

**Comment by NikolaiVChr** [comment]
Fixed, thank you
