### ISSUE TITLE
FGAddon: AGM-65.ac missing

### ISSUE THREAD

**Issue by NikolaiVChr** [NikolaiVChr/f16#331]
This is likely a linux case sensitivity issue..is why we haven't seen it.

**Comment by JMaverick16** [comment]
Missing? Strange.

**Comment by NikolaiVChr** [comment]
Its your stores branch that was causing it.
Exception: Model file not found: 'AGM-65.ac' at .../AGM-65/AGM-65D.xml

**Comment by JMaverick16** [comment]
It's been fixed in a recent commit
