### ISSUE TITLE
AGM-65 WPN MFD page: PWR ON and Ripple

### ISSUE THREAD

**Issue by JMaverick16** [NikolaiVChr/f16#332]

**Comment by NikolaiVChr** [comment]
No clue what this is about as there is no description.

**Comment by JMaverick16** [comment]
Basically implementing functions in the WPN page for the Mavericks to program them. I saw some info in the F-16CJ manual about the various modes present.

**Comment by NikolaiVChr** [comment]
38f755f7a80956061ce02f7048b0a3a49cd365db

**Comment by JMaverick16** [comment]
![Screenshot_20210119-125404.png](https://user-images.githubusercontent.com/10477466/105031481-a6ace200-5a55-11eb-829f-7fc8839b00ac.png)
Screenshot from Wags DCS tutorial of what I'm referring to.

**Comment by NikolaiVChr** [comment]
Not going to do this, as it would require a rewrite of portions of the fire-control code.
Stuff like this is really super luxery and not needed.

**Comment by JMaverick16** [comment]
But but... Oh well. Giving more use to WPN page isn't so luxury IMO.
