### ISSUE TITLE
HUD: Add A/G gunsight crosshair

### ISSUE THREAD

**Issue by JMaverick16** [NikolaiVChr/f16#337]
So to speak:
![2021-01-12_211535](https://user-images.githubusercontent.com/10477466/104372037-3287b100-5520-11eb-9d4a-ceb905427cd9.png)
Pic by cactus from BMS to show the point.

Because using the EEGS for strafing isn't really practical.

**Comment by NikolaiVChr** [comment]
8169cfc96c517b0b31f3026b26b3c7fc24066523

**Comment by NikolaiVChr** [comment]
The real one has range of 4000ft, so fly slow :)

**Comment by NikolaiVChr** [comment]
![image](https://user-images.githubusercontent.com/3764194/104816281-6dd4f900-581a-11eb-85e8-e11a1b24efaf.png)
