### ISSUE TITLE
Tacview: update code from the illuminator

### ISSUE THREAD

**Issue by JMaverick16** [NikolaiVChr/f16#343]
Since we can't always ping an admin to make it record things, especially on public MP, it would be better for it to be up to date so users can record their sessions at best.

**Comment by NikolaiVChr** [comment]
Can you please list the things that do not work with the f16 tacview?

**Comment by JMaverick16** [comment]
It's been quite a bit so I don't really remember. I know there are some things which on the F-16 don't show up but that been told the Illuminator has, so would be better to backport the ones which are compatible.

**Comment by NikolaiVChr** [comment]
Now should work better on public servers.
On OPRF servers still a bit limited.
