### ISSUE TITLE
Dialogs Control Panel Left / Right and Center lagging behind controls in cockpit

### ISSUE THREAD

**Issue by ph-jake** [NikolaiVChr/f16#344]
The Control Panel dialogs, accessed from the F-16 menu, in category 'Main', present alternative means of manipulating cockpit controls. In recent times the number of active cockpit controls has expanded while others have gained additional functionality. This is not reflected in these dialogs. This issue is to track that the dialogs are updated to mimic the full extend of the cockpit controls.

**Comment by NikolaiVChr** [comment]
I would rather remove all the menu dialogs. Problem solved. :)

**Comment by JMaverick16** [comment]
As Leto said, these will eventually get discontinued, therefore closing the issue
