### ISSUE TITLE
License: GPL 2.0

### ISSUE THREAD

**Issue by NikolaiVChr** [NikolaiVChr/f16#345]
Except for a copy of the license text the aircraft do not offer details about license.

GPL 2 offer a possibility to declare its license like this:

```
This program is free software; you can redistribute it and/or
modify it under the terms of the GNU General Public License
as published by the Free Software Foundation; either version 2
of the License, or (at your option) any later version.
```

Anyone of you object to adding that?

I will ask Erik also.

Furthermore I think FGAddon/FG is declared like that, so its only proper to add it (although I personally don't like v3). It will give an option for v3 aircraft to borrow stuff from the F-16.

**Comment by legoboyvdlp** [comment]
I have no objection to my work.

**Comment by NikolaiVChr** [comment]
Erik approved, said he always intended it to be v2.0+

Here is the full text we need to add, for example to readme.md

Putting only Erik's name is easier than putting 30 names, and he is the original author.

```
Copyright (C) 2021  Erik Hofman

This program is free software; you can redistribute it and/or
modify it under the terms of the GNU General Public License
as published by the Free Software Foundation; either version 2
of the License, or (at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program; if not, write to the Free Software
Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
```

**Comment by ph-jake** [comment]
Personally I don't like these blobs of legalese adding nothing of technical value to the code. Therefore my preference is to add the [SPDX](https://spdx.dev) id and get it over with. It's a well accepted license reference, maintained by a Linux Foundation project. In this case it would be:

`# SPDX-License-Identifier: GPL-2.0-or-later`

Simple, one line and you're done.

**Comment by NikolaiVChr** [comment]
JMav agree also.

Jake, I prefer to do it, like GNU license text say it should be done.
