### ISSUE TITLE
Compositor: Missing shader ubershader.{vert,frag}

### ISSUE THREAD

**Issue by colingeniet** [NikolaiVChr/f16#347]
On branch `compositor2`, effects `flir/flir-mfd.eff` and `fuselage/model-combined-turbine.eff` use `ubershader.{vert,frag}`, which no longer exist in FGData on `next`.

**Comment by NikolaiVChr** [comment]
Thanks

**Comment by NikolaiVChr** [comment]
03ae59a73cf099f7a6fa7ea48174a224c85103a9 should fix this

**Comment by colingeniet** [comment]
Works for me.
