### ISSUE TITLE
DED: IFF page says NO CONN even when selecting a target with same code

### ISSUE THREAD

**Issue by JMaverick16** [NikolaiVChr/f16#353]

**Comment by SammySkycrafts** [comment]
Seen Earlier today, We both had same IFF Code. Latest pull at the time.
![image](https://user-images.githubusercontent.com/77464976/117370835-e2fa3600-aebe-11eb-9781-a8cfeeda5c3e.png)

**Comment by NikolaiVChr** [comment]
NO CONN means no DLINK connection. Not to be confused with IFF. IFF you need to ask query him.
