### ISSUE TITLE
AGM-158: weapon has IR terminal guidance mode

### ISSUE THREAD

**Issue by JMaverick16** [NikolaiVChr/f16#366]
![Screenshot_20210511-213012.png](https://user-images.githubusercontent.com/10477466/118647439-a1805980-b7e1-11eb-9b88-30df222710df.png)

https://forgehub-prod.s3.amazonaws.com/media/cache/0a/29/0a29444d0918ee0cf395d98ec641160b.jpg

Second photo shows the IR seeker head

**Comment by NikolaiVChr** [comment]
That fine I confirmed it, but that source is from a sim, or? Can we please fully stop quoting other sims as source of info.
If you find something in them, find a real source of it also please.

**Comment by JMaverick16** [comment]
Nope it wasn't from a simulator. I don't remember exactly where I found it cause it was a few weeks ago but the source was credible.
