### ISSUE TITLE
Laser CCRP seems broken for TGP point

### ISSUE THREAD

**Issue by NikolaiVChr** [NikolaiVChr/f16#373]
Reported by: Fox Three

**Comment by NikolaiVChr** [comment]
Due to 
me.slave_to_radar?math.min(me.max_seeker_dev, me.fcs_fov):me.max_seeker_dev

<FCS-field-deg type="int"> 200 </FCS-field-deg>
<seeker-field-deg type="int"> 32 </seeker-field-deg>

This has to be thought through, me.max_seeker_dev should be obeyed not until after dropping, where its nose down will cause it to gain lock.

**Comment by JMaverick16** [comment]
This is where it apparently got broken according to Sammy: 5b80a90b801b78fa15c83be1fc189b2ddf14734c

**Comment by JMaverick16** [comment]
Testing produced positive results, hence it's a fix. Closing
