### ISSUE TITLE
radarSystem: HMCS doesn't work on the Radar Branch

### ISSUE THREAD

**Issue by TotallyRealElonMusk** [NikolaiVChr/f16#376]
Sometimes, the HMCS just freezes on the radar branch for no reason. No way to fix it, just have to turn it off. Its very annoying :(

![image](https://user-images.githubusercontent.com/72507855/138508908-4271ade8-a32c-4334-92cf-7f59a326e227.png)

**Comment by NikolaiVChr** [comment]
Can you attach a log of such a flight please?
That would help me.

**Comment by NikolaiVChr** [comment]
7413722 fixed this
