### ISSUE TITLE
Arms: AGM-65 consistently overflies target and hits shortly after it

### ISSUE THREAD

**Issue by JMaverick16** [NikolaiVChr/f16#377]
Console doesn't give any errors nor there seems to be an apparent reason for it. I've been noticing it for quite a bit now after several tries. It once required me all 6 Mavericks to destroy a Shilka (with multiple combined partial damages); IR POINT lock was present all the time.

**Comment by JMaverick16** [comment]
Did further testing yesterday with different launch techniques (high, low, dive, etc) and they are indeed not working.
By looking at the explosion on TGP it seems like the bounce off the target and hit some 20/30 meters afterward.

**Comment by NikolaiVChr** [comment]
I think this is due to having the tgp make the lock 1 meter above ground. Since there is no collision with the target it will fly through it, and explode on the other side, when it hits the ground.

**Comment by NikolaiVChr** [comment]
f8c5035ce5a38614d2272a4daa86bfee2e39428e hopefully fixes this

**Comment by JMaverick16** [comment]
After further testing yesterday it seemed to be still present when targeting Shilkas in Hunter.

**Comment by NikolaiVChr** [comment]
I need to see a damage log also, so how many meters it missed with.

**Comment by NikolaiVChr** [comment]
And your framerate while it hit

**Comment by JMaverick16** [comment]
damage log said 10 and 52m hits, while fps was around 10 or so.

**Comment by NikolaiVChr** [comment]
Might be fixed now, time will tell I guess.

**Comment by NikolaiVChr** [comment]
This is mostly an issue with your very low FPS.

Switched them to APN from PN guidance-law. So they don't have to make so much last-minute adjustments to hit, which should help on low fps machines.

**Comment by NikolaiVChr** [comment]
Okay, further investigation into this.

`Terminal 1.70 mach.`

I suggest trying to increase the coeff from 0.06 to at least 0.15 or higher.

They are way too fast I think, the slower they go, the easier they they can adjust to hit.

**Comment by JMaverick16** [comment]
Works like a charm after latest changes. Closing
