### ISSUE TITLE
Arms: AGM-88 flies straight after lock and launch

### ISSUE THREAD

**Issue by JMaverick16** [NikolaiVChr/f16#378]
This one yet needs more tests, but so far every launch to a SAM went without guidance and the missile flying inertially to the ground.

**Comment by SammySkycrafts** [comment]
Tested 19/12 With a Non-Shooting SAM and it worked fine. Second test conducted on 20/12 with a Shooting SAM and that too worked fine with both missiles tracking as expected to the SAM Site.

**Comment by NikolaiVChr** [comment]
Seems it works, closing for now
