### ISSUE TITLE
How to change the default payload in the f-16 block-52

### ISSUE THREAD

**Issue by dk-raw** [NikolaiVChr/f16#379]
I was wondering if there is an easy way of changing the default payload settings(weapon, pods, fuel tanks) in the F-16 Block-52 so I don't have to go through the fuel and payload settings every time I fly the F-16.

**Comment by JMaverick16** [comment]
F-16 Dialog > Payload presets. You click on the one you wish.

All of them are based on real life docs and reference photos.

**Comment by dk-raw** [comment]
Can I create a custom one though?

**Comment by JMaverick16** [comment]
If you want to mess with the code yes.
Else you have to go back to the fuel and payload dialog and edit manually your loads

**Comment by NikolaiVChr** [comment]
You will have to edit Nasal code to do that.
Some configurations is not possible though due to the way xml for graphics is setup to support just the configs we use.
But maybe if you can document that your config was/is actually used, maybe Jmav16 can be convinced to add it.

**Comment by JMaverick16** [comment]
Closing as the subject remained unanswered.
