### ISSUE TITLE
f16 cockpit panels_mlu_right-console and joystick position error

### ISSUE THREAD

**Issue by unsanedingding** [NikolaiVChr/f16#381]
Left/right console panels is  lower than expected 20cm,  maybe i miss something? And  throttle joystick positon error too....
Thank you very much!

**Comment by NikolaiVChr** [comment]
Could you tell us what version of f16 you are using.
Where/when did you download it from, and what's your FG version?

**Comment by unsanedingding** [comment]
Thank you!
1)FlightGear2020.4.0 , I get it from ( https://github.com/FlightGear/flightgear) 'next' branch.
2)f16 come from (https://github.com/NikolaiVChr/f16   ( master)
3)and I use "fgdata\Aircraft\f16\Models\F-16.xml"

**Comment by unsanedingding** [comment]
almost ready, i guess it's a rotate question
