### ISSUE TITLE
radarSystem: Stutters and freezes when turning radar to operational from standby

### ISSUE THREAD

**Issue by NikolaiVChr** [NikolaiVChr/f16#410]
![image](https://user-images.githubusercontent.com/3764194/147854822-2b78bce9-d356-4261-8250-c74a0361fce0.png)

**Comment by NikolaiVChr** [comment]
Seems somewhat relieved a bit by e9d2be34a325c42e54d67e29fccbd1409e0c5eb0

**Comment by JMaverick16** [comment]
After a recent test it didn't get relieved at all unfortunately, had a 2-minute freeze earlier after enabling radar while pointing the nose 35/40 deg up after takeoff. Seems like it tends to freeze more often when there are other people online.

**Comment by NikolaiVChr** [comment]
Hopefully fixed by 61998178667b9c9799efbb7705516e5c1c948065
