### ISSUE TITLE
TGP: Add Modifier to movement via Arrow Keys on Keyboard

### ISSUE THREAD

**Issue by SammySkycrafts** [NikolaiVChr/f16#413]
When the TGP is at 1x zoom and wide then the rate of movement is fine when using arrow keys but when the TGP is set to Narrow and / or zoomed in its very slow and sometimes is unusable due to the speed.

**Comment by NikolaiVChr** [comment]
I just looked at the code and did some tests.
The slewing of the camera is set to be exactly the same no matter zoom.
And it works that way too.
At least when you hold down the cursor slew keys. As for clicking the keys then its up in the air to what happens.
So what you are asking for is already implemented.
Holding a key for about 1 second will move about ½ the screen no matter the zoom level.

If you experience something else, then any chance you could record a video of it?

**Comment by NikolaiVChr** [comment]
I have added possibility to start FG with this option, which will modify TGP speed:
`--prop:/controls/displays/tgp-movement-modifier=1.25`

**Comment by NikolaiVChr** [comment]
This issue has a deeper problem.
It seems in some flights its slow, some flights it works fine.

**Comment by NikolaiVChr** [comment]
Hopefully this was remedied by 4f79ca0fdef4acbd4047eea24d3534d380ec4617
Can I close this issue?

**Comment by SammySkycrafts** [comment]
Seems fine now - I'm happy for this to be closed.
