### ISSUE TITLE
Roll indicator arrow is on wrong side of scale

### ISSUE THREAD

**Issue by NikolaiVChr** [NikolaiVChr/f16#415]
It should be below and the ticks should be smaller.

**Comment by legoboyvdlp** [comment]
Good spot. 
![image](https://user-images.githubusercontent.com/10434911/148238943-123ddd90-2565-4cd4-8a84-bc89cfdf5023.png)

There should be 9 ticks. There should not be a duplicated tick at the center.
![image](https://user-images.githubusercontent.com/10434911/148239075-89630358-2f19-4492-bd8d-f54b0f07efc5.png)

**Comment by legoboyvdlp** [comment]
![image](https://user-images.githubusercontent.com/10434911/148240704-586e431d-5a37-4c95-bbb4-eb97e766e9a6.png)

**Comment by legoboyvdlp** [comment]
Also tics / dots drawn around the flight path marker: 
![image](https://user-images.githubusercontent.com/10434911/148241182-0739bc22-b9e0-41d8-80f8-05f6f12c760c.png)

It is shown when the switch is in VV/VAH and flight path marker is shown. 

![image](https://user-images.githubusercontent.com/10434911/148241669-9d649a80-4dc7-4aad-afa2-2b4a59f742e7.png)

**Comment by NikolaiVChr** [comment]
fixed
