### ISSUE TITLE
A/P STG SEL don't follow to active custom steerpoint

### ISSUE THREAD

**Issue by NikolaiVChr** [NikolaiVChr/f16#419]

**Comment by NikolaiVChr** [comment]
Not sure how Josh's A/P find out what to navigate to.

**Comment by NikolaiVChr** [comment]
@Octal450 any suggestions?

**Comment by Octal450** [comment]
@NikolaiVChr Do you want to keep Route manager compatibility?
We have 2 options here:

Option 1: Use your custom navigation, and if that is not set, then try route manager
Option 2: Use only your custom navigation

Then in either case, just provide me with properties for the heading to fly (true or mag, I can do either) and whether or not a point is set, and I can update the A/P to use them.

Kind Regards,
Josh

**Comment by NikolaiVChr** [comment]
Hmnm, maybe use only my nasal code.

You can use the above code to get heading.

**Comment by Octal450** [comment]
OK.

Kind Regards,
Josh

**Comment by NikolaiVChr** [comment]
Fixed with 31333a17
