### ISSUE TITLE
radarSystem: Hot MP F-14 not picked up

### ISSUE THREAD

**Issue by NikolaiVChr** [NikolaiVChr/f16#430]
Fox-three:
I had another situation where I was heads on with a hot F-14 (coming in from my front to 1 o clock) and never saw a blip.
We were both at around 40k ft. I checked with the map map at around 27 nm separation.
radar range was 40. We were heads on from 50+nm separation all the way down to him splashing me at around 18.

Referencing this issue (#391), because both are very clear conditions, where something that should very easily get picked up just doesn't.

**Comment by NikolaiVChr** [comment]
I need a bit more info:
Which radar mode? And was it A6, B4?
When had you last updated the aircraft? Last bugfix was like 3 hours before you reported this.

**Comment by JMaverick16** [comment]
It happened to me as well against Johan's Viggen in ACM 20 DGFT mode. Flew dead ahead for about 15nm all the way till merge without picking anything up. Were were same alt and I had visual on him in the center of my HUD thanks to his contrail. Seems pretty much the same issue

**Comment by NikolaiVChr** [comment]
No recent problems.
