### ISSUE TITLE
Datalink targets only show on the FCR when radar is active

### ISSUE THREAD

**Issue by NikolaiVChr** [NikolaiVChr/f16#446]
Datalink targets only show on the FCR when radar is active. Wingmen show fine in both silent and active

**Comment by SammySkycrafts** [comment]
Both examples of this issue:

![unknown-152.png](https://user-images.githubusercontent.com/77464976/150659309-39ddfedc-3b4b-418f-b6e7-9f33ececaad7.png)![unknown-151.png](https://user-images.githubusercontent.com/77464976/150659310-f5a1e780-0a5c-4c0f-b69e-1f86b97ae3e3.png)

**Comment by NikolaiVChr** [comment]
Hopefully fixed now.
