### ISSUE TITLE
3D: Ext gear doors have odd way of displaying the effect

### ISSUE THREAD

**Issue by JMaverick16** [NikolaiVChr/f16#449]
![Schermata 2022-01-23 alle 23 55 38](https://user-images.githubusercontent.com/10477466/150701835-8f16c814-a88e-4dbe-8866-c4f6663f27f2.png)
![Schermata 2022-01-23 alle 23 56 43](https://user-images.githubusercontent.com/10477466/150701841-abceb855-c70b-4f10-b186-981ee0845c74.png)

**Comment by NikolaiVChr** [comment]
Semi-fixed now
