### ISSUE TITLE
DTC: More stuff

### ISSUE THREAD

**Issue by NikolaiVChr** [NikolaiVChr/f16#452]
- [x] COM channel frequencies
- [x] HSD lines 1/2
- [x] Bullseye
- [x] Threat circles
- [x] Markpoints
- [x] Weapon GPS
- [x] Route
- [x] Transponder Mode 3
- [x] Transponder Mode 4
- [x] Datalink code
- [x] ALOW
- [x] BINGO
- [x] DLINK
- [x] DTE MFD Page

**Comment by JMaverick16** [comment]
Updated with list

**Comment by JMaverick16** [comment]
BINGO isn't set by DTC while MSL Floor is.

**Comment by NikolaiVChr** [comment]
> BINGO isn't set by DTC while MSL Floor is.

No, its opposite
![image](https://user-images.githubusercontent.com/3764194/179051218-94107339-4caf-4d69-9baa-d1c0b3396404.png)

**Comment by NikolaiVChr** [comment]
And what do you mean by floor?

**Comment by NikolaiVChr** [comment]
TF-MSL-FLOOR is not saved in DTC

**Comment by JMaverick16** [comment]
Not the TF one, the other.

**Comment by NikolaiVChr** [comment]
Not saved either

**Comment by JMaverick16** [comment]
Completed for now, will open new issues if deemed necessary
