### ISSUE TITLE
Animate gear collapse when parameters are met

### ISSUE THREAD

**Issue by JMaverick16** [NikolaiVChr/f16#461]
Right now it collapses without visible animation, probably the animation used in the F-15 could help.

**Comment by NikolaiVChr** [comment]
Duplicate of #76

**Comment by JMaverick16** [comment]
This was actually meant as visually seeing the gear break apart and collapsing, not just the code.

**Comment by NikolaiVChr** [comment]
Its a duplicate thats what the other is about too.
