### ISSUE TITLE
ICP: Hack timer appears to be broken

### ISSUE THREAD

**Issue by SammySkycrafts** [NikolaiVChr/f16#462]
As above - Its not even possible to scroll on the TIME page on the ICP using the usual arrow, 0 doesnt do anything either.

**Comment by NikolaiVChr** [comment]
Use this to control hack, works as it should, closing issue.
![image](https://user-images.githubusercontent.com/3764194/154903750-fc28bd12-435d-4088-859e-3190956a81b7.png)
