### ISSUE TITLE
Datalink buddies not showing on FCR / HSD

### ISSUE THREAD

**Issue by SammySkycrafts** [NikolaiVChr/f16#467]
Datalink buddies are not showing on the FCR or HSD, except when you have radar contact on them. The buddy also reported not being able to see me until I got radar contact on them. Often they do appear later on though when radar isnt painting them in any way.

Datalink targets (Locked up by buddies) do appear to show though, even when buddy is not visible
![Screen Shot 2022-03-06 at 16 32 13](https://user-images.githubusercontent.com/77464976/157057842-47715d3c-785e-4e11-b117-34117f4c8e6b.png)
![Screen Shot 2022-03-06 at 16 31 48](https://user-images.githubusercontent.com/77464976/157057879-65b06329-2457-47ce-90f3-51efb8a62f27.png)
e

**Comment by NikolaiVChr** [comment]
You need line of sight on them. Could that be the issue?

**Comment by SammySkycrafts** [comment]
I cannot reproduce either - its been working again a while. May have just been LOS as you said.
