### ISSUE TITLE
F16 "auto start"

### ISSUE THREAD

**Issue by unsanedingding** [NikolaiVChr/f16#474]
I want to reduce "auto start" wait time in my test, I notice some parament of time in states_and_autostart.nas , and try to modify it, but fail....

Thank you.

**Comment by unsanedingding** [comment]
Thank you, but, if i want to reduce wait time for test HUD changed by my self ..... modify "time speed"?
thanks agiain.

**Comment by JMaverick16** [comment]
You can simply start the sim in "ready for take off" mode so the jet is already started up when spawning in.
