### ISSUE TITLE
MLW: Random Missile Launch Warnings heard and printed in eventlog.

### ISSUE THREAD

**Issue by SammySkycrafts** [NikolaiVChr/f16#475]
MLW's were noted by multiple people, and seen in event logs from different people. None of those had any weapons that could produce this (A/G Training loadout and MK-82's loaded in addition). 
![image](https://user-images.githubusercontent.com/77464976/172254173-aa5dbcbf-c3ac-4ef2-81ef-d8c8297d1bb6.png)
![image](https://user-images.githubusercontent.com/77464976/172254198-4a1212f6-2162-43e4-8a83-a9ed28e8f7b2.png)
As seen in below screenshot, VooDoo3 had no weapons that could produce this. (I had the identical loadout)
![image](https://user-images.githubusercontent.com/77464976/172254256-4b971b66-da47-48dd-bc7b-6f9f5d854530.png)

**Comment by NikolaiVChr** [comment]
I see at least 3 weapons that can produce that. But you say they were not fired?

**Comment by NikolaiVChr** [comment]
It might be a bug in Hunter, if it was helis that launched at you..

**Comment by SammySkycrafts** [comment]
> I see at least 3 weapons that can produce that. But you say they were not fired?

Only thing there that could be released was the MK-82s. On the wingtip points there was CATM-120's, the first pylons were CATM-9 and an ACMI pod. (A/G Training preset).

>It might be a bug in Hunter, if it was helis that launched at you.

The scenario that was active only contained non-shooting ground assets (croatia) - the Heli's have now been split into a different scenario (kornati)

**Comment by NikolaiVChr** [comment]
Hmmm, strange.
Sounds like something got broken.. It should only be produced by a weapon that have an active exhaust.

**Comment by NikolaiVChr** [comment]
I cannot reproduce.

If you can then, in damage.nas uncomment this: 
```javascript
print("recv(d1): ",notification.NotificationType, " ", notification.Ident,
                      " UniqueIdentity=",notification.UniqueIdentity,
                      " Kind=",notification.Kind,
                      " SecondaryKind=",notification.SecondaryKind,
                      " lat=",notification.Position.lat(),
                      " lon=",notification.Position.lon(),
                      " alt=",notification.Position.alt(),
                      " u_fps=",notification.u_fps,
                      " Heading=",notification.Heading,
                      " Pitch=",notification.Pitch,
                      " IsDistinct=",notification.IsDistinct,
                      " Callsign=",notification.Callsign,
                      " RemoteCallsign=",notification.RemoteCallsign,
                      " Flags=",notification.Flags,
                      " Radar=",bits.test(notification.Flags, 0),
                      " Thrust=",bits.test(notification.Flags, 1));
```
In the aircraft that receives the mlw WARNING.
Then when you get the warning, look in console and see if it looks like this (Thrust=0):
```
  135.23 [INFO]:nasal      recv(d1): ArmamentInFlightNotification mp-bridge UniqueIdentity=-96 Kind=2 SecondaryKind=53 lat=46.02338 lon=12.58391299999999 alt=96 u_fps=26.36889008911703 Heading=46.2 Pitch=-86.95652173913045 IsDistinct=0 Callsign=Leto2 RemoteCallsign= Flags=0 Radar=0 Thrust=0
```
SecondaryKind=53 means its a MK-82

**Comment by NikolaiVChr** [comment]
This still an issue?

**Comment by SammySkycrafts** [comment]
Haven't noticed it since.
