### ISSUE TITLE
F-16 "jsb-controls.xml" and "fcs/fly-by-wire/tef/tef-pos-norm"

### ISSUE THREAD

**Issue by unsanedingding** [NikolaiVChr/f16#479]
In my test case, i lost "fcs/fly-by-wire/tef/tef-pos-norm" at Runtime,  and notice "fcs/fly-by-wire/tef" and childs Property was define at "jsb-controls.xml"...
 
but i cann't  catch jsb-constrols .xml was loaded  where or when   (by debug BreakPoint in VS2019)? 
 
I searched "f16-simplified" , "f16-simplified-set",  i dont know "jsb-controls.xml" were referenced by where?

 Thank you.

**Comment by SammySkycrafts** [comment]
JSB-controls.xml is located in /systems

It's called in the fdm configuration file (f16blkXX.xml) located in the f16 directory root.

**Comment by NikolaiVChr** [comment]
If the issue was that the sim complained at startup about missing property, it should be fixed now.

Which block did you experience the problem in?

**Comment by unsanedingding** [comment]
Thanks again.

1. After begin startup FG, in this function i get a exception, (PropertyName is "fcs/fly-by-wire/tef/tef-pos-norm ")
FGPropertyNode* FGPropertyValue::GetNode(void) const
{
  if (!PropertyNode) {
    FGPropertyNode* node = PropertyManager->GetNode(PropertyName);
    
    if (!node)
      throw(std::string("FGPropertyValue::GetValue() The property " +
                        PropertyName + " does not exist."));

    PropertyNode = node;
  }

2.  FG(F16) has NOT this propblem , Only in my test case (F16 +JSBSim + FGData(Root)), But, Maybe my question is :
   Where and When were Load"fcs/fly-by-wire/tef/tef-pos-norm" OR "jsb-constrols.xml"  ? Because in "Update" fcs/fly-by- 
  wire/tef/tef-pos-norm"  property must exist, but i don't know where load "jsb-constrols.xm".

3. I set Debug breakpoint in vs2019 at "bool FGFDMExec::LoadModel(const string& model, bool addModelToPath)"
   but , in this function, "jsb-constrols.xml" was not Loaded, So , I'm very confuse.....

**Comment by NikolaiVChr** [comment]
jsb-controls.xml is not loaded in f16 simplified.

Its a mistake the property was used in that f16.

There is also an error in the simplified fuel system.

The simplified f16 is hard to maintain, as it uses a different fdm and different controls.

Will look into it.
