### ISSUE TITLE
F16  About C++/Nasal Quesiton :   " NasalCanvas ::  f_canvasCreateGroup " Not Called

### ISSUE THREAD

**Issue by unsanedingding** [NikolaiVChr/f16#480]
In my test Case :
1.  C++ debug breakPoint mode all "f_canvasCreateGroup" function cannot called , But f_createCanvas and child/Element node can be called (can be new/created), 

2. I notice "f_canvasCreateGroup" has already "Registed" .(FG at left, My Test Project at Right)

![3b1a4cd024fa033190697f726848a53](https://user-images.githubusercontent.com/26058055/174509112-d834155d-1c45-42ee-b954-5909894ad5a2.png)

So, Can you give me some hints  In C++ side ?

**Comment by NikolaiVChr** [comment]
We are not so used to look at the C++ side of things, we mostly do stuff in Nasal or XML.
So I am not sure we can help you.
I would try ask in devel list: https://wiki.flightgear.org/Mailing_lists

**Comment by unsanedingding** [comment]
Thank you.
