### ISSUE TITLE
The Queestion about f16 FCS in jsbsim

### ISSUE THREAD

**Issue by ybrv587** [NikolaiVChr/f16#483]
Hello,Nikolai.
I'm sorry to bother you.Recently I wanted to reproduce the FCS of F16 using Simulink, but I wanted to consult the references you mentioned in your report and only found two of them, TP-1538&TN-D8176.I can't find AD-A055-417, AD-A189-675&ICAS-90-5.10.2. Could you please send me a relevant document?By the way, do you have the structure diagram of the FCS you built in JSBsim? If possible, I would like to refer to it,It will be helpful for me to understand your FCS.You can email me directly at 524583666@qq.com .Thank you again.

**Comment by NikolaiVChr** [comment]
I have not made a diagram of the implementation, no.
As for finding references, Nasa Technical Document Server is a good place to start.

**Comment by NikolaiVChr** [comment]
As for the diagram, ADA055-417 has the diagram that most of the control stuff is based on. Since yesterday it is now also based on ADA189-675.

If you are just going to use it in simulink while flying and not do takeoff or landings, I suggest you just use TP-1538 diagrams as  they are simplified only for flying.

**Comment by NikolaiVChr** [comment]
I made a diagram of some of the new changes by LJQC, maybe it will help you a bit if you don't decide to go with TP-1538:

![A-DA189-675-by-LJQC-pitch](https://user-images.githubusercontent.com/3764194/177129853-de95602a-a5c6-4e8f-abe5-2da73037c484.png)

**Comment by ybrv587** [comment]
Thanks for your reply,NikolaiVChr.
I have initially built the control loop of F16 according to TP-1538 and applied it to flight simulation.With your help, I should be able to improve it. Thank you again for your generous help.
Regards.

**Comment by JMaverick16** [comment]
After about a year I would assume this is solved, closing.
