### ISSUE TITLE
JFS1 remains on after engine restart

### ISSUE THREAD

**Issue by JMaverick16** [NikolaiVChr/f16#484]
After crashing and repairing (without JFS recharge) and possibly after normal shutdown and restart, auto startup is happening on JFS1, which doesn't automatically disable itself after the procedure is complete.

**Comment by NikolaiVChr** [comment]
Its due to this line: `if (me.wow and me.n2 >= 55) {` in engine.nas
It will only auto switch back if wheel are on ground.
As far as I remember that is correct behavior.
So when your airborne and starting engine, you have to manually switch it back.
