### ISSUE TITLE
HMCS: Show more info

### ISSUE THREAD

**Issue by JMaverick16** [NikolaiVChr/f16#486]
- [x] Bullseye info
- [x] STPT symbol
- [ ] heading tape

**Comment by NikolaiVChr** [comment]
![image](https://user-images.githubusercontent.com/3764194/176774392-6299bdaf-66ca-43ab-8bbb-ca8510291cf3.png)

**Comment by NikolaiVChr** [comment]
Highest threat seems to be a very new feature (if it exist). And so wont make.

**Comment by NikolaiVChr** [comment]
No clue what you mean by **loft cue and such**.

**Comment by NikolaiVChr** [comment]
Not sure what you mean by **STPT data**, stpt info is already displayed.

**Comment by JMaverick16** [comment]
> No clue what you mean by **loft cue and such**.
The DLZ range scale (40) that we talked about with Sammy the other day, unsure if it's already implemented so I wrote here too.

> Not sure what you mean by **STPT data**, stpt info is already displayed.

Sammy brought this up in Discord.

**Comment by NikolaiVChr** [comment]
Don't think loft cue is displayed in HMCS, also don't really make sense, its for long range aim-120 engagements.

**Comment by JMaverick16** [comment]
Then unless what Sammy said is different from what we have now and there aren't ant other things to add I'd say it's good.

**Comment by NikolaiVChr** [comment]
He probably meant STPT symbol, not STPT data..

**Comment by JMaverick16** [comment]
That should do.
