### ISSUE TITLE
HMCS: Ability to create markpoints and heading tape

### ISSUE THREAD

**Issue by JMaverick16** [NikolaiVChr/f16#491]
It would require picking a proper key to create MKPTs, suggestions are welcome.

- [x] Markpoints
- [x] Heading tape

**Comment by NikolaiVChr** [comment]
![image](https://user-images.githubusercontent.com/3764194/177263944-0c330e44-aa2f-4b1b-9f20-4f556920990b.png)

**Comment by NikolaiVChr** [comment]
How about:
1: Make HUD SOI
2: Click `l` (lima)

Simple and in line with our current system, until we remake it..

**Comment by NikolaiVChr** [comment]
Markpoints made: 280762eff9e552c89532d58c66c15f205a7d9fcc
