### ISSUE TITLE
Question: About .ac file in xml

### ISSUE THREAD

**Issue by unsanedingding** [NikolaiVChr/f16#497]
I notice hud.ac was define in hud.xml and hud_basic.xml, and i debug trace in FG (C++ ), i found .ac was loaded two times....so, I'm very confuse, and in fact more about hud content(.ac) was loaded (f16_war_hud.ac in f16_war_hud.xml and f16_war_basic.ac)..... 

like this:
 <path>hud.ac</path> in hud.xml and hud_basic.xml
<path>f16_war_hud.ac</path> in f16_war_hud.xml and f16_war_basic.xml

All of them(.xml) was loaded in C++.

1)More than one HudImage2 submodel and Canvas object in HUD Model (from multi times reference)  was apply in F16?

**Comment by NikolaiVChr** [comment]
That is correct.

In the menu you can switch between basic (Intel graphics card compatible) and normal huds.
So we load the ac 2 times and switch which one you see depending on which shader we put on it.
Even though this sounds bloated, its the cleanest way to do that in FG as we see it.

The war (wide angle raster) hud similarly has 2 versions; basic and normal. They are also both loaded. Shown only on block 40 and 42 though.

**Comment by unsanedingding** [comment]
Similar question ， also include tractor at load f16-simplified(and f16-simplified-set.xml), In my test cast ,when i load f16-simplified, i get f16 and tractor (geen color wrapper), and parachute.....

So, Have(or need) a switch can close these widget(tractor  and parachute) in FG?

**Comment by NikolaiVChr** [comment]
I have no clue what tractor you refer to. What tractor? Can you paste an image?

The pilot have a parachute in all blocks and versions.

**Comment by unsanedingding** [comment]
![1658909517(1)](https://user-images.githubusercontent.com/26058055/181196546-f1de8273-c619-4ecc-ab45-14d1bee23cd9.png)

**Comment by NikolaiVChr** [comment]
To remove it, just toggle Pushback

![image](https://user-images.githubusercontent.com/3764194/181203991-b9c149a9-b08c-4f21-a044-909eb6d68a2e.png)
