### ISSUE TITLE
Shaders: NVG's incompatible with HMCS

### ISSUE THREAD

**Issue by SammySkycrafts** [NikolaiVChr/f16#499]
NVG's incompatible with HMCS - The shaders switch to a high intensity "default" shader that provides amazing vision at night outside, but washes all of the pit's lights out and is is highly unrealistic. can only be reset by pressing the "reset shaders". See attached screenshots
![Screen Shot 2022-09-28 at 19 40 29](https://user-images.githubusercontent.com/77464976/193426018-e941c915-42b5-4a15-ad4a-63f8982c7ba4.png)
![Screen Shot 2022-09-28 at 19 40 31](https://user-images.githubusercontent.com/77464976/193426020-c2039d45-93f6-4313-a19c-a3713e8e670c.png)

**Comment by Rudolf339** [comment]
JHMCS is physically incompatible with the NVG anyway, you can only attach one of them to the helmet at a time :wink: 

(Might have been resolved with newer generation of HMCS introuduced very recently)

**Comment by NikolaiVChr** [comment]
Cant be mixed
