### ISSUE TITLE
When landing with correct AoA it can be hard to see touchdown point.

### ISSUE THREAD

**Issue by NikolaiVChr** [NikolaiVChr/f16#50]
This is an issue that involves many things. Such as moving viewpoint (which means chaging 3D of cockpit so MFDs RWR can be seen clearly. It might also involve changing the HUD model a bit to keep bore symbol inside it.

**Comment by NikolaiVChr** [comment]
Okay, made an attempt at fixing this. At 15 deg AoA it can still be hard, but at 11-12 its kinda doable now.

**Comment by JMaverick16** [comment]
Will this still be addressed? Right now I don't see it as an issue. Unless maybe increasing FoV or pushing default view a bit upwards and backwards.

**Comment by JMaverick16** [comment]
I've recently pushed the seat up by a very little margin and for me it isn't an issue at all. Unless somebody brings this up again I'll close it.
