### ISSUE TITLE
Stores: Impact listener not detecting impact with some stores

### ISSUE THREAD

**Issue by SammySkycrafts** [NikolaiVChr/f16#501]
Impact not being correctly reported leading to no damage on intended target / limited damage being dealt to surrounding targets. Guidance is not affected, all affected weapons guide correctly.

Currently affected weapons: 

- AGM-65B
- AGM-65D
- GBU-12
- GBU-24

Multiple hits on same target with nothing at all in event log and no damage transmitted. 

![unknown](https://user-images.githubusercontent.com/77464976/194580925-9d005cb0-9be5-4708-828f-21a3d2def82e.png)

**Comment by NikolaiVChr** [comment]
Fixed with e3389e874bf2f3b52944e8a3af957ca3a449bc54
