### ISSUE TITLE
GBU-54: Improve LJDAM guidance system

### ISSUE THREAD

**Issue by JMaverick16** [NikolaiVChr/f16#506]
Should have the ability to switch between GPS and/or laser guidance. An MFD control key could toggle that.

**Comment by NikolaiVChr** [comment]
1. So MFD GBU-54 setting with 2 options: LASR, GPS
2. In missile-code, make guidance mode "gps-laser", which will be able to hit movable targets when laser is detected.
3. To keep it simple codingwise MFD setting applies per bomb for now.
4. Should lock even if no laser present.

**Comment by NikolaiVChr** [comment]
Fixed, need testing that GPS-LASR can hit moving target..
