### ISSUE TITLE
Cockpit: Add CDU to Block 60, certain Block 50/52

### ISSUE THREAD

**Issue by JMaverick16** [NikolaiVChr/f16#508]
Would need a 3D model of the frame to fit in the top map screen, digital artificial horizon and EHSI.
Block 60 has it standard, certain wings are being converted (169FW, 20FW, 52FW, VFC-13).

**Comment by SP-NTX** [comment]
Can you see a photo/drawing of it? i can try to do it

**Comment by SammySkycrafts** [comment]
> Can you send a photo/drawing of it? i can try to do it

@SP-NTX References have been posted in 3D Work > #cockpit in the F-16 Development server.

**Comment by NikolaiVChr** [comment]
Aerotronics sim version of Raytheon version:
![image](https://user-images.githubusercontent.com/3764194/209528438-8ed64505-ea38-40df-a3a1-13e75d8a505b.png)
![image](https://user-images.githubusercontent.com/3764194/209528460-b0f73df6-efc1-4a5c-b367-84fe04230633.png)

169fw:
![image](https://user-images.githubusercontent.com/3764194/209528637-07bfa723-d3db-422d-86c6-e77750f01994.png)
![image](https://user-images.githubusercontent.com/3764194/209528672-78bd2cce-9ad0-462f-a8a2-514266d41419.png)

![image](https://user-images.githubusercontent.com/3764194/209528871-7a385f34-0eb4-4ef3-9a03-d70630a5c8e1.png)

Lockheed:
![image](https://user-images.githubusercontent.com/3764194/209528991-ae38be09-127c-4940-a288-03451c68eadf.png)

Elbit F-16V:
![image](https://user-images.githubusercontent.com/3764194/209529112-6d527f93-da98-4e95-ae47-4af9b8565e65.png)

System Program Office
![image](https://user-images.githubusercontent.com/3764194/209530006-651aa3a7-d0ac-4efe-8c67-beae66188a15.png)
![image](https://user-images.githubusercontent.com/3764194/209530049-3449f4ad-2052-4a5f-957b-ea8326592e7d.png)

**Comment by NikolaiVChr** [comment]
Block 40:
![image](https://user-images.githubusercontent.com/3764194/209530370-db8d4f71-ab17-4da8-94d6-56582df42943.png)

Block 50:
![image](https://user-images.githubusercontent.com/3764194/209530507-2ed23b83-e497-4132-ac7d-a7c61f8126a9.png)

Other style:
![image](https://user-images.githubusercontent.com/3764194/209530648-0eec2683-3e62-446f-b3f0-6bf3a0d69e41.png)

**Comment by NikolaiVChr** [comment]
![image](https://user-images.githubusercontent.com/3764194/209530995-f3b8444e-5d53-43cc-b5c7-7279b16a96f5.png)

**Comment by NikolaiVChr** [comment]
Mount should be 160mm wide and use the design of the last picture above.
Display object should be 140mm x 175mm and be named cdu_canvas.
Edge button objects should be numbered 1 to 8 downwards on left side, 9 to 16 downwards on right side, 17 to 21 on top and 22 to 26 at bottom.
HSI controls should be named: HSI_hdg-knob, HSI_course-knob and button.
Fuel knob should be named FQS_sel-knob.

**Comment by NikolaiVChr** [comment]
I have started writting the logic for it, hence why I'm particular especially about the size.

**Comment by SP-NTX** [comment]
im starting working on it
Should i also texture it?

**Comment by NikolaiVChr** [comment]
If you want to. We will be happy about the 3D alone whether textured or not, or UV mapped or not.
I don't know how experienced you are in UV mapping, but a good advice is to UV map the buttons before you duplicate them around the panel, so you don't have to UV map 26 buttons separately.
Btw. The little greenish square in lower left corner is likely a light for indicating beacon markers, just so you know how to name it.
