### ISSUE TITLE
HMCS: Temporary disable if NVG filter is activated.

### ISSUE THREAD

**Issue by JMaverick16** [NikolaiVChr/f16#509]

**Comment by NikolaiVChr** [comment]
NVG cannot be enabled when using HMCS, has been like that since I made the HMCS. Whats wrong with that?

**Comment by JMaverick16** [comment]
Just check, that's true, my bad.
Although when having HMCS on, turning NVGs on when the view is default and then moving around with brightness maxed out it removes the NVG but the brightness slider doesn't reset.

**Comment by NikolaiVChr** [comment]
The brightness slider is not controlled by aircraft, as it gets saved. So it would influence user settings for other aircraft.

**Comment by JMaverick16** [comment]
Copy, thanks for the clarification.
