### ISSUE TITLE
DED: Add DTC MISC page w/ working A/C TAIL field.

### ISSUE THREAD

**Issue by JMaverick16** [NikolaiVChr/f16#510]
<img width="550" alt="Schermata 2022-12-28 alle 00 47 28" src="https://user-images.githubusercontent.com/10477466/209737137-304e7050-7e65-401f-b291-b4b5ae1c91e3.png">
Will try to make it automatically pick the serial entered inside the livery tag, or something like that, as per MLU M3.

**Comment by NikolaiVChr** [comment]
This is easy to make, have fun.

**Comment by JMaverick16** [comment]
Done via [542043d](https://github.com/NikolaiVChr/f16/commit/542043dd3eccbc7e209924a4e13b25265c7be153)
