### ISSUE TITLE
RWR: Improve Threat Warning Prime functioning

### ISSUE THREAD

**Issue by JMaverick16** [NikolaiVChr/f16#514]

**Comment by NikolaiVChr** [comment]
Made the SEP button work:
![image](https://github.com/NikolaiVChr/f16/assets/3764194/4bf53f8d-bd21-4f55-b143-925a2a26329b)

**Comment by NikolaiVChr** [comment]
It does however separate in both azimuth and radius, while the real one only separates in radius.
