### ISSUE TITLE
AIM-120 Maddog kills the teammates

### ISSUE THREAD

**Issue by Developer0607** [NikolaiVChr/f16#515]
In the combat, AIM-120 Maddog release can lock on persons who use the same IFF and DataLink channel as mine. Should maddogs pay attention to IFF?

**Comment by NikolaiVChr** [comment]
Not sure, almost everything about them is classified.

**Comment by SammySkycrafts** [comment]
Recommending issue closure. AIM-120's have no way of identifying friend from foe. That's one of the reasons you don't shoot into a furball.
