### ISSUE TITLE
AIM-120 fired at scenario opponent crashes fg

### ISSUE THREAD

**Issue by NikolaiVChr** [NikolaiVChr/f16#517]
AIM-120 fired at scenario 0 opponent crashes fg if it hits.

**Comment by BobDotCom** [comment]
I cannot reproduce this issue (see here: https://discord.com/channels/379782363061813248/496121096492417025/1098660482384138261). If anyone has detailed reproduction steps that would be really helpful, otherwise this can probably be closed if the bug no longer occurs.

**Comment by sryu1** [comment]
I was able to reproduce it a few months ago but after that, didn't really do that scenario, I'll try again when I get some time.

**Comment by BobDotCom** [comment]
Might be safe to close this unless someone can reproduce it, I can't seem to find any way to trigger it.
