### ISSUE TITLE
FlightGear Ardupilot SITL for custom UAV 

### ISSUE THREAD

**Issue by akshaydhame2001** [NikolaiVChr/f16#523]
1)How to simulate a multirotor fixed wing UAV modelled in CATIA with FlightGear simulator and Ardupilot SITL? 
2)Which files need to be generated while importing it from CATIA to FlightGear?
3)How to generate an XML file for UAV.
I just tried replacing c172p.ac with my model.ac, editing fg_plane_view batch file --aircraft=c172p(My model was renamed) and running sim_vehicle.py

**Comment by NikolaiVChr** [comment]
I recommend asking this in https://forum.flightgear.org instead.
