### ISSUE TITLE
Question:About  coordinate system of .ac in FG

### ISSUE THREAD

**Issue by unsanedingding** [NikolaiVChr/f16#526]
Only a question:

I'm very confuse, Is all .ac model use standand RightHand coordinate? When i try  to convert it to LeftHand 
 coordinate system, always fail...

thank you.

**Comment by NikolaiVChr** [comment]
When you import an ac model into for example Blender or Flightgear, you will see right-handed:

Backwards in aircraft: +X
Right in aircraft: +Y
Up in aircraft: +X

But inside the AC file itself its also right-handed, but flipped 90 degrees:

Backwards in aircraft: +X
Right in aircraft: -Z
Up in aircraft: +Y

**Comment by unsanedingding** [comment]
Thanks a lot.
