### ISSUE TITLE
Question: About MFD

### ISSUE THREAD

**Issue by unsanedingding** [NikolaiVChr/f16#529]
I notice the 2 'T' at above picture.And have some questions:
1.  In mfd_left.nas , what is the "T" ,  is this a cursor ? svg.cursor?
2.  How does the "T" move , use svg update? or animation?(But in mfd_left.xml, i saw the animation has deleted...)

Thank you.

**Comment by legoboyvdlp** [comment]
I believe the T shows the current azimuth and elevation of the radar antenna. I can't help you as to how it is created.

**Comment by unsanedingding** [comment]
Thanks .
