### ISSUE TITLE
Question: About isEnabled: func {} of APG68.nas

### ISSUE THREAD

**Issue by unsanedingding** [NikolaiVChr/f16#531]
I noticed getprop("/fdm/jsbsim/gear/unit[0]/WOW") in isEnabled func; in my test cast the prop always "1", so ,always failed this conditional test.(In isEnabled func, the prop must be seted "0").

Question: where is prop("/fdm/jsbsim/gear/unit[0]/WOW") be setted？ Or, what error cause the prop value error?

Thanks NikolaiVChr.

**Comment by SammySkycrafts** [comment]
It is the Weight on Wheels sensor - So the radar is inhibited when on ground for safety. To have the value set to 0 then you need to remove the weight on the wheels (Takeoff)

**Comment by unsanedingding** [comment]
> 
Thanks .
