### ISSUE TITLE
Laser guided bombs target radar lock instead of TGP lock

### ISSUE THREAD

**Issue by NikolaiVChr** [NikolaiVChr/f16#532]
Reported by @BobDotCom 

Only fails below 5000 ft.

Temp work-around: Undesignate radar lock before dropping.

**Comment by BobDotCom** [comment]
Doesn't fix it for me. Additionally, I believe the issue also occurred with GPS guided munitions (though I'd have to check).

**Comment by NikolaiVChr** [comment]
I just made a commit, any chance you could check if the issue is solved?
Please fly with this line set to 1 in missile_code.nas:
`var DEBUG_STATS            = 0;#most basic stuff`

In case it is not solved, please note the output in console, especially this line:
`Note: Ordnance was released locked on this target type: ?`

Also also if it say it changed target and lost/reacquired lock during the drop.

**Comment by NikolaiVChr** [comment]
Fixed, hopefully.
