### ISSUE TITLE
Refuel broken

### ISSUE THREAD

**Issue by NikolaiVChr** [NikolaiVChr/f16#54]
Spectre reports refuel is broken.

Needs confirmation and possible fix.

**Comment by Zaretto** [comment]
Refuel tested and working 2018.3.1 (RC)

However unattached tanks are refueled; probably these should be disabled/deselected when not on the stores list. On the F-15 I set the maximum capacity of these tanks to zero dynamically based on configuration.

**Comment by NikolaiVChr** [comment]
Thanks

**Comment by NikolaiVChr** [comment]
So I see that I actually already do those things (in /consumables anyway) except it was not done at startup.

Is it enough to do it in /consumables or?

**Comment by NikolaiVChr** [comment]
Fixed hopefully.
