### ISSUE TITLE
MFD SIT page crashes when typing in route

### ISSUE THREAD

**Issue by NikolaiVChr** [NikolaiVChr/f16#55]
Type in FTTY as destination to provoke error. @Zaretto has been informed.

**Comment by Zaretto** [comment]
Which FG version is this; I just tried with my 2018.4 (i.e. next build) at I don't see an error

**Comment by Zaretto** [comment]
Seems to work in 2018.4; I'll try 2018.2.x next

![image](https://user-images.githubusercontent.com/2045654/46244405-dba54e80-c3de-11e8-90d3-e49cf774b6eb.png)

**Comment by Zaretto** [comment]
pushed a fix to fgdata for this.

**Comment by NikolaiVChr** [comment]
Fix works for me.

**Comment by Zaretto** [comment]
Should now be merged into 2018.3

**Comment by NikolaiVChr** [comment]
great! closing
