### ISSUE TITLE
Flightgear reset not effect when using F16

### ISSUE THREAD

**Issue by ujust4fun** [NikolaiVChr/f16#571]
Hi. I am using the F16 addon in the FG2020.3 version. I added the command option --start=cruise to start the FlightGear. However, the new f16 state is unstable and the avionics have not been activated after I click the reset button.  I have checked the nas script in F16 folder but did not find a suitable option to the reset "key is shift-esc".

**Comment by SammySkycrafts** [comment]
The reset button breaks parts of the F-16's code. It should not be used. If you need to repair / move then use Location > select airport.

**Comment by ujust4fun** [comment]
thank you!
