### ISSUE TITLE
Question : Missiles Attachment/Detachment 

### ISSUE THREAD

**Issue by unsanedingding** [NikolaiVChr/f16#574]
I noticed some infomation in F-16.xml:
....
 <model>
  <name>AN_ALQ-184</name>
  <path>Aircraft/f16/Models/Armament/External-stores/AN_ALQ-184/AN_ALQ-184.xml</path>
  <offsets>
   <x-m>0.265</x-m>
   <y-m>0</y-m>
   <z-m>-1.0215</z-m>
   <pitch-deg>-0.6</pitch-deg>
  </offsets>
 </model>

 <model>
  <name>VentralTank</name>
  <path>Aircraft/f16/Models/Armament/External-stores/Fueltanks/300G.xml</path>
  <offsets>
   <x-m>-0.055</x-m>
   <y-m>0</y-m>
   <z-m>-1.21</z-m>
   <pitch-deg>-2</pitch-deg>
  </offsets>
 </model>
....

My Question is : Which .nas or .xml controll these missiles attachement / detachment,  because in my test case , all missiles were loaded with aircaft, So I want to known how to detachment(or hide them).

Thank you.

**Comment by NikolaiVChr** [comment]
In the userinterface they are controlled from Menu->Fuel and Payloads
Otherwise its from pylons.nas
