### ISSUE TITLE
MFD: TGP button doesn't work on Thrustmaster Cougar MFDs

### ISSUE THREAD

**Issue by JMaverick16** [NikolaiVChr/f16#580]
Pressing to OSB enter TGP provides the upper "Click BACK..." but no view, while if going there from the in-game MFD and later clicking BACK from the physical works.

**Comment by NikolaiVChr** [comment]
And another thing, is there an error in the console?

**Comment by JMaverick16** [comment]
Closing this as it has been since then solved.
