### ISSUE TITLE
Many of the liveries have inverted or disjoined text

### ISSUE THREAD

**Issue by NikolaiVChr** [NikolaiVChr/f16#59]
Here is some examples:

![image](https://user-images.githubusercontent.com/3764194/46269586-7bc7b880-c542-11e8-9da1-297991cc50e7.png)

![image](https://user-images.githubusercontent.com/3764194/46269665-ed076b80-c542-11e8-9f8f-7c7af22cc07b.png)

![image](https://user-images.githubusercontent.com/3764194/46269735-453e6d80-c543-11e8-92a7-c235ce70ce59.png)

![image](https://user-images.githubusercontent.com/3764194/46269744-54bdb680-c543-11e8-8710-93625987d27e.png)

![image](https://user-images.githubusercontent.com/3764194/46269777-8e8ebd00-c543-11e8-90c0-bb60bcaf7c9d.png)

**Comment by NikolaiVChr** [comment]
Fixed:
rnlaf orange lion b20
rnlaf demo b20
rnlaf block 10
indonesian b20
3x italian b20
one of the aggresor ghosts

**Comment by JMaverick16** [comment]
Disjoined texts will hopefully be solved with fixes to the 3D model.

**Comment by NikolaiVChr** [comment]
mostly fixed as good as the models allow for now.
