### ISSUE TITLE
Gear produce friction and triggers weight-on-wheel while airborne

### ISSUE THREAD

**Issue by NikolaiVChr** [NikolaiVChr/f16#596]
Happened to me only once, but I have seen that bug before in JA37.

![fgfs-20240514030319](https://github.com/NikolaiVChr/f16/assets/3764194/0bb2423e-1341-48df-92b6-0923d7f825f6)

**Comment by SammySkycrafts** [comment]
It happens to me most when I retract my gear immediately after takeoff, for example if you put the gear handle up on the ground and let the wheels auto retract.

**Comment by NikolaiVChr** [comment]
Okay, thanks.
