### ISSUE TITLE
Put Spectre's new engine and wheel textures into all liveries

### ISSUE THREAD

**Issue by NikolaiVChr** [NikolaiVChr/f16#61]
It looks great, so why not..

**Comment by NikolaiVChr** [comment]
Done for all my liveries.

**Comment by NikolaiVChr** [comment]
Wheel and engine fire is now taken from f16.png. And can no longer be custom to liveries.
The outlet turbine is still dependent on liveries.

**Comment by JMaverick16** [comment]
I guess this is sorted as of now right? Intake texture should be done when 3D works are done for a real spinning fan.

**Comment by JMaverick16** [comment]
All liveries include those plus updates ones I've made so closing this
