### ISSUE TITLE
Review all store and launcher drag and mass

### ISSUE THREAD

**Issue by NikolaiVChr** [NikolaiVChr/f16#62]
This has not really been looked at since the system was made, it needs a review.

**Comment by JMaverick16** [comment]
I have reviewed a few of them, mainly dummies and pods, but most are a guess.

**Comment by NikolaiVChr** [comment]
All those zero mass rack/pylons needs something.

**Comment by JMaverick16** [comment]
I'll need to look after data for those hopefully from the docs you sent me.

**Comment by JMaverick16** [comment]
Weights have been added according to the 2009 weapons file.

**Comment by NikolaiVChr** [comment]
This has been done last year.
