### ISSUE TITLE
New duo and tri-racks (and mounted on the wing pylons)

### ISSUE THREAD

**Issue by NikolaiVChr** [NikolaiVChr/f16#70]
duo has been made (twinrack.ac), needs to be textured.

**Comment by JMaverick16** [comment]
This will require exterior 3D rework first. Hopefully, Martien will start once I hear back from him.

**Comment by NikolaiVChr** [comment]
Triple rack TER-9A is textured and ready.
Duo rack need texturing.

**Comment by NikolaiVChr** [comment]
* [x] GBU-12
* [ ] MK-82
* [ ] AGM-65B
* [ ] AGM-65D

**Comment by NikolaiVChr** [comment]
Fixed for triracks.

**Comment by JMaverick16** [comment]
AGM-65 trio has their own set of rail rack, needs to be modelled.
TER-9A needs to be implemented on LAU-68 still.
BRU-57 for L-JDAMs.

**Comment by JMaverick16** [comment]
BRU-57 has been fielded on CBU-105s as well, the only thing missing is the specific AGM-65 triple rail system which we don't have models for.
Closing since it's pretty much completed now
