### ISSUE TITLE
HUD frozen

### ISSUE THREAD

**Issue by legoboyvdlp** [NikolaiVChr/f16#73]
bug: if you are locked on someone who disconnects, the HUD will freeze for ~5 sec

**Comment by NikolaiVChr** [comment]
need FG version.

**Comment by legoboyvdlp** [comment]
2018.4

**Comment by Shaym0** [comment]
i can confirm

**Comment by NikolaiVChr** [comment]
3.1? 2018.3.1?

**Comment by NikolaiVChr** [comment]
Cannot confirm on 2018.3.1

Need more details on how to reproduce. Does this happen all the time, or only sometimes? Do you use DDS cache? What settings do you have set in the controlpanel etc?

**Comment by Shaym0** [comment]
im unshure it only happened once on that vers, and i use quickstart so the default settings for block 52

**Comment by legoboyvdlp** [comment]
2018.3.1

I do not use DDS cache.

I don't have the other info.
