### ISSUE TITLE
RWR: Only show threats. And unknown very rarely (if at all)

### ISSUE THREAD

**Issue by NikolaiVChr** [NikolaiVChr/f16#77]
Unknown needs to go or be strongly filtered.

**Comment by NikolaiVChr** [comment]
Unknown will go away.

Only airborne search radars, threat aircraft and ground based anti-air should be shown.

Question is, do we show aircraft that would be a threat IRL or only those that is a threat in FG.

**Comment by JMaverick16** [comment]
I'm for situational awareness, so I'd say all airliners (unknown) out and keep the present threats list as is if not even expand it to a wider range of a/c, especially since it's not only and OPRF but also an FGAddon plane.

**Comment by NikolaiVChr** [comment]
Good point.

**Comment by NikolaiVChr** [comment]
Unknowns removed.
Tankers removed.
Bombers removed.
Truck removed.

Use the radar for those. Only entities that has anti-air capability or AWACS stayed. And as you suggested those that has them only in RL stays too.
