### ISSUE TITLE
Improve CBU-87 drop simulation

### ISSUE THREAD

**Issue by JMaverick16** [NikolaiVChr/f16#79]
Create fragmentation of bomb casing and cluster units after some time elapsed after drop (could be also linked to alt?).

**Comment by NikolaiVChr** [comment]
In theory this could be done with submodels. It might get heavy on FPS though.

**Comment by JMaverick16** [comment]
Best way would be having this mid-way between performance and nice rendering, obviously.

**Comment by NikolaiVChr** [comment]
Well for performance could use particle effect. Then the submodels wont be 3D but a flat 2D texture always billboarded at viewer.

**Comment by JMaverick16** [comment]
@NikolaiVChr I have implemented the explosion effect from the Viggen's M90, tested and works but somehow the explosion effect is "tilted" and not horizontal and sometimes explodes before reaching the ground. Requires verification.

**Comment by NikolaiVChr** [comment]
I think M90 has a property in its missile stats that sets that it should
align itself to the ground.

>

**Comment by JMaverick16** [comment]
Oh, so as I wondered it might be linked to the bomb spinning animation? Or just another thing?

**Comment by NikolaiVChr** [comment]
Try set spin to zero

>

**Comment by JMaverick16** [comment]
I will try, although that will not be realistic as CBUs are meant to spin harder to disperse better the bomblets.

**Comment by JMaverick16** [comment]
So with spin set to 0 it all works, I've adapted the explosion to the CBU-87 characteristics. So for now I'd close this issue and eventually open a new one for further bomblet dispensing effect.
