### ISSUE TITLE
Missile code terminal guidance for big ordnance

### ISSUE THREAD

**Issue by NikolaiVChr** [NikolaiVChr/f16#83]
Its too rescricted for JASSM, it will overshoot target often.

**Comment by JMaverick16** [comment]
Don't know if it affects bombs also, but with the JSOW coming along it should be taken in consideration too.

**Comment by NikolaiVChr** [comment]
Only cruise/glide missiles

**Comment by JMaverick16** [comment]
The JSOW should be included being able to glide to target from 80NM of dropped at max alt

**Comment by NikolaiVChr** [comment]
Should be fixed now, needs testing.

**Comment by NikolaiVChr** [comment]
Only if it terrain follows, does it do that?

**Comment by NikolaiVChr** [comment]
seems to work, closing issue.
