### ISSUE TITLE
Remove GUI options for stuff that can be done in 3D

### ISSUE THREAD

**Issue by NikolaiVChr** [NikolaiVChr/f16#85]
For example engine start can done be done in 3D.

**Comment by NikolaiVChr** [comment]
Not sure, we want to ever remove the menu dialogs.
Whats peoples opinion on this?

**Comment by JMaverick16** [comment]
Instead of removing GUI maybe add more functionalities over 3D. But I think that removing things is something that can he done at a later date. Also, the control panel menus are too nice to get rid of them IMO.

**Comment by NikolaiVChr** [comment]
We probably never want to do this, so closing.
